[omxh264dec]
type-name=GstOMXH264Dec
core-name=/usr/lib/libOmxCore.so
component-name=OMX.qcom.video.decoder.avc
rank=258
in-port-index=0
out-port-index=1
#hacks=no-disable-outport;no-empty-eos-buffer
hacks=no-disable-outport
#sink-template-caps=video/x-h264,stream-format=(string)avc,alignment=(string)au,level=(string)2.1,profile=(string)constrained-baseline
#src-template-caps=video/x-raw-yuv,width=(int)[16,4096],height=(int)[16,4096],framerate=(fraction)[0,max],format=(string){I420,YUY2,UYVY,NV12}

[omxh263dec]
type-name=GstOMXH263Dec
core-name=/usr/lib/libOmxCore.so
component-name=OMX.qcom.video.decoder.h263
rank=258
in-port-index=0
out-port-index=1
hacks=no-disable-outport;no-empty-eos-buffer

#[omxaacdec]
#type-name=GstOMXAACDec
#core-name=/usr/lib/libOmxCore.so
#component-name=OMX.qcom.audio.decoder.aac
#rank=256
#in-port-index=0
#out-port-index=1
#hacks=no-disable-outport;no-empty-eos-buffer

[omxmpeg4videodec]
type-name=GstOMXMPEG4VideoDec
core-name=/usr/lib/libOmxCore.so
component-name=OMX.qcom.video.decoder.mpeg4
rank=258
in-port-index=0
out-port-index=1
hacks=no-disable-outport;no-empty-eos-buffer

[omxmpeg2dec]
type-name=GstOMXMPEG2VideoDec
core-name=/usr/lib/libOmxCore.so
component-name=OMX.qcom.video.decoder.mpeg2
rank=258
in-port-index=0
out-port-index=1
hacks=no-disable-outport;no-empty-eos-buffer

[omxwmvdec]
type-name=GstOMXWMVDec
core-name=/usr/lib/libOmxCore.so
component-name=
rank=258
in-port-index=0
out-port-index=1
hacks=no-disable-outport;no-empty-eos-buffer

[omxh264enc]
type-name=GstOMXH264Enc
core-name=/usr/lib/libOmxCore.so
component-name=OMX.qcom.video.encoder.avc
rank=256
in-port-index=0
out-port-index=1
hacks=no-disable-outport;no-empty-eos-buffer

[omxh263enc]
type-name=GstOMXH263Enc
core-name=/usr/lib/libOmxCore.so
component-name=OMX.qcom.video.encoder.h263
rank=256
in-port-index=0
out-port-index=1
hacks=no-disable-outport;no-empty-eos-buffer

#[omxaacenc]
#type-name=GstOMXAACEnc
#core-name=/usr/lib/libOmxCore.so
#component-name=OMX.qcom.audio.encoder.aac
#rank=256
#in-port-index=0
#out-port-index=1
#hacks=no-disable-outport;no-empty-eos-buffer

[omxmpeg4videoenc]
type-name=GstOMXMPEG4VideoEnc
core-name=/usr/lib/libOmxCore.so
component-name=OMX.qcom.video.encoder.mpeg4
rank=256
in-port-index=0
out-port-index=1
hacks=no-disable-outport;no-empty-eos-buffer

[omxh265enc]
type-name=GstOMXH265Enc
core-name=/usr/lib/libOmxCore.so
component-name=OMX.qcom.video.encoder.hevc
rank=256
in-port-index=0
out-port-index=1
hacks=no-disable-outport;no-empty-eos-buffer


