#!/bin/sh
# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

export MODULE_BASE=/usr/lib/modules/`uname -r`/

echo "Loading coresight module: " > /dev/kmsg
insmod $MODULE_BASE/coresight.ko
insmod $MODULE_BASE/coresight-etb10.ko
insmod $MODULE_BASE/coresight-tpiu.ko
insmod $MODULE_BASE/coresight-stm.ko
insmod $MODULE_BASE/coresight-tgu.ko
insmod $MODULE_BASE/coresight-etm4x.ko
insmod $MODULE_BASE/coresight-funnel.ko
insmod $MODULE_BASE/coresight-remote-etm.ko
insmod $MODULE_BASE/coresight-cti.ko
insmod $MODULE_BASE/coresight-tpdm.ko
insmod $MODULE_BASE/coresight-tpda.ko
insmod $MODULE_BASE/coresight-replicator.ko
insmod $MODULE_BASE/coresight-csr.ko
insmod $MODULE_BASE/coresight-dummy.ko
insmod $MODULE_BASE/coresight-tmc.ko
insmod $MODULE_BASE/coresight-cpu-debug.ko
insmod $MODULE_BASE/coresight-catu.ko
insmod $MODULE_BASE/coresight-tmc-sec.ko
echo "Finished loading coresight module" > /dev/kmsg
