kernel.trace_buf_size = "128M"
kernel.trace_clock = "global"
# ftrace.tracer = "function_graph"

# ===== UFS =====
ftrace.event.ufs.enable = "1"
ftrace.event.ufsqcom.enable = "1"
# ftrace.ftrace.filters = "ufshcd_queuecommand"

# ===== Scheduler =====
ftrace.event.sched.sched_process_exit.enable = "1"
ftrace.event.sched.sched_process_free.enable = "1"
ftrace.event.sched.sched_blocked_reason.enable = "1"
ftrace.event.sched.sched_waking.enable = "1"
ftrace.event.sched.sched_wakeup_new.enable = "1"
ftrace.event.sched.sched_wakeup.enable = "1"
ftrace.event.sched.sched_switch.enable = "1"

# ===== Task =====
ftrace.event.task.task_newtask.enable = "1"
ftrace.event.task.task_rename.enable = "1"

# ===== Power =====
ftrace.event.power.cpu_frequency.enable = "1"
ftrace.event.power.cpu_idle.enable = "1"
ftrace.event.power.suspend_resume.enable = "1"

# ===== IRQ / SoftIRQ =====
ftrace.event.irq.irq_handler_entry.enable = "1"
ftrace.event.irq.irq_handler_exit.enable = "1"
ftrace.event.irq.softirq_raise.enable = "1"
ftrace.event.irq.softirq_entry.enable = "1"
ftrace.event.irq.softirq_exit.enable = "1"
