kernel.trace_buf_size = "128M"
kernel.trace_clock = "global"
# ftrace.tracer = "function_graph"

# ===== UFS =====
ftrace.event.ufs.enable = "1"
ftrace.event.ufsqcom.enable = "1"
# ftrace.ftrace.filters = "ufshcd_queuecommand"

# ===== Scheduler =====
ftrace.event.sched.sched_process_exit.enable = "1"
ftrace.event.sched.sched_process_free.enable = "1"
ftrace.event.sched.sched_blocked_reason.enable = "1"
ftrace.event.sched.sched_waking.enable = "1"
ftrace.event.sched.sched_wakeup_new.enable = "1"
ftrace.event.sched.sched_wakeup.enable = "1"
ftrace.event.sched.sched_switch.enable = "1"
ftrace.event.sched.sched_pi_setprio.enable = "1"
ftrace.event.sched.sched_migrate_task.enable = "1"

# ===== Task =====
ftrace.event.task.task_newtask.enable = "1"
ftrace.event.task.task_rename.enable = "1"

# ===== Power =====
ftrace.event.power.cpu_frequency.enable = "1"
ftrace.event.power.cpu_idle.enable = "1"
ftrace.event.power.suspend_resume.enable = "1"

# ===== IRQ / SoftIRQ =====
ftrace.event.irq.irq_handler_entry.enable = "1"
ftrace.event.irq.irq_handler_exit.enable = "1"
ftrace.event.irq.softirq_raise.enable = "1"
ftrace.event.irq.softirq_entry.enable = "1"
ftrace.event.irq.softirq_exit.enable = "1"

# ===== Watchdog / IPI =====
ftrace.event.watchdog.enable = "1"
ftrace.event.ipi.enable = "1"

# ===== Workqueue =====
ftrace.event.workqueue.workqueue_queue_work.enable = "1"
ftrace.event.workqueue.workqueue_execute_start.enable = "1"
ftrace.event.workqueue.workqueue_execute_end.enable = "1"

# ===== Timer =====
ftrace.event.timer.timer_expire_entry.enable = "1"
ftrace.event.timer.timer_expire_exit.enable = "1"
ftrace.event.timer.hrtimer_cancel.enable = "1"
ftrace.event.timer.hrtimer_expire_entry.enable = "1"
ftrace.event.timer.hrtimer_expire_exit.enable = "1"
ftrace.event.timer.hrtimer_setup.enable = "1"
ftrace.event.timer.hrtimer_start.enable = "1"
