# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.

#Conf file to load security-driver modules at boot-up time
#Install under /etc/modules-load-d/ path
qseecom_dlkm
tz_log_dlkm
qrng_dlkm
smcinvoke_dlkm
