# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"
BSPDIR := "${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)) + '/../../..')}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "qti-tgvm"
BBFILE_PATTERN_qti-tgvm = "^${LAYERDIR}/"
BBFILE_PRIORITY_qti-tgvm = "10"

LAYERSERIES_COMPAT_qti-tgvm = "kirkstone"

LAYERDEPENDS_qti-tgvm = "core openembedded-layer networking-layer multimedia-layer qti-tgvm-prop"

LICENSE_PATH += "${LAYERDIR}/files/common-licenses"

# Currently edk2 need python2 to support compilation
HOSTTOOLS_NONFATAL += "python python2"

QTI_METAPATH_BASE := '${@os.path.normpath("${LAYERDIR}/")}'
QTI_LICENSE_DIR = "${QTI_METAPATH_BASE}/files/common-licenses"
