# Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
[Service]
Environment="WESTON_MODULE_MAP="drm-backend.so=@sdm_ext_dir/drm-backend.so;sdm-service.so=@sdm_ext_dir/sdm-service.so;gbm-buffer-backend.so=@sdm_ext_dir/gbm-buffer-backend.so;screen-capture.so=@sdm_ext_dir/screen-capture.so""
Environment="LD_LIBRARY_PATH="@sdm_ext_dir:""
