# Use a local timeserver
server 192.168.100.2 noselect

# Sync the start of second using PPS
refclock PPS /dev/pps0 refid KPPS trust lock GNSS

# GNSS time
refclock SOCK /var/run/chrony.sock refid GNSS maxdispersion 0.2 noselect

# Always step the system clock if the adjustment is larger
# than 100 milliseconds.
makestep 0.1 -1

# Record the rate at which the system clock gains/loses time,
# improving accuracy after reboot
driftfile /data/chrony/drift

# Serve time even if not synchronized to any NTP server.
local stratum 10

# Allow NTP client access from local network.
allow all
