#! /bin/sh
#Copyright (c) 2021 The Linux Foundation. All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are
#met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#      with the distribution.
#    * Neither the name of The Linux Foundation nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
#WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
#ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
#OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
#IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/bin/mount -a
/bin/busybox --install
/bin/mount -t sysfs none /sys
/bin/mount -t debugfs debugfs /sys/kernel/debug
/bin/mount -t tracefs tracefs /sys/kernel/debug/tracing > /dev/null 2>&1
/sbin/mdev -s
/bin/echo /sbin/mdev > /proc/sys/kernel/hotplug

# This is necessary to emulate the android environment expected by adbd
echo "Configuring the environment to support 'adb shell' ..."
mkdir /dev/pts
mount -t devpts devpts /dev/pts
chmod 0666 /dev/ptmx
mkdir -p /system/bin
ln -s /bin/sh /system/bin/sh
chmod 4755 /bin/su

# get soc platform
if [ -f /sys/devices/soc0/hw_platform ]; then
	socplatform=`cat /sys/devices/soc0/machine` 2> /dev/null
else
	socplatform=`cat /sys/devices/system/soc/soc0/machine` 2> /dev/null
fi
echo "soc:" $socplatform

# find serialno from cmdline
cmdline=`cat /proc/cmdline` 2> /dev/null
strsearch="androidboot.serialno="
if echo "$cmdline" | grep -q "$strsearch"; then
	startsearch=${cmdline#*$strsearch}
	pos=$(( ${#cmdline} - ${#startsearch}))
	serialno=${cmdline:$pos:8}
else
	echo "serialno not found with cmdline, use default"
	serialno="12345678"
fi

echo "serialno:" $serialno
mount -t configfs none /sys/kernel/config
if [ -d /sys/kernel/config/usb_gadget ]; then
	echo "Configuring the USB gadget using ConfigFS..."
	cd /sys/kernel/config/usb_gadget
	mkdir g1
	cd g1
	mkdir strings/0x409
	mkdir configs/c.1
	mkdir configs/c.1/strings/0x409
	mkdir functions/ffs.adb

	echo "$serialno" > strings/0x409/serialnumber
	echo "QTI" > strings/0x409/manufacturer
	echo "$socplatform" > strings/0x409/product
	echo 0x18d1 > /sys/kernel/config/usb_gadget/g1/idVendor
	echo 0x4E11 > /sys/kernel/config/usb_gadget/g1/idProduct
	echo "ADB" > configs/c.1/strings/0x409/configuration
else
	echo "Configuring the USB gadget using legcy method..."
	cd /sys/class/android_usb/android0/
	echo 0 > enable
	echo 05C6 > idVendor
	echo 901D > idProduct
	echo "$serialno" > iSerial
	echo "QTI" > iManufacturer
	echo "$socplatform" > iProduct
	echo diag > f_diag/clients
	echo diag,ffs > functions
	echo 1 > enable
fi

echo "Configuring FunctionFS endpoints for adbd..."
if [ ! -d /dev/usb-ffs/adb ]; then
    mkdir -p /dev/usb-ffs/adb
fi
if [ ! -e /dev/usb-ffs/adb/ep0 ]; then
    mount -o uid=2000,gid=2000 -t functionfs adb /dev/usb-ffs/adb
fi

echo "Launching adbd..."
/sbin/adbd &

if [ -d /sys/kernel/config/usb_gadget ]; then
	ln -s functions/ffs.adb configs/c.1/f1
	sleep 1
	udcname=`ls -1 /sys/class/udc | head -n 1`
	echo "binding UDC with Gadget..." $udcname
	echo $udcname > UDC
fi

