require ${QTI_METAPATH_DISTRO}/conf/distro/auto-agl.conf

PRODUCT = "${MACHINE}agldemo"

# Tweaked version of what's in poky-agl.conf, need AGL_APP_REVISION
# for SRCREV in demo binding and application recipes.
AGLVERSION = "11.0.0"
AGL_DISTRO_BRANCH_VERSION_TAG = "${AGL_BRANCH}/${@'${AGLVERSION}'.replace('+snapshot-${DATE}','')}"
AGL_APP_REVISION := "refs/tags/${AGL_DISTRO_BRANCH_VERSION_TAG}"

# Complementary package definition for agl-devel-wgt image feature
COMPLEMENTARY_GLOB[agl-devel-wgt] = '*-coverage *-debug'

# For building with meta-app-framework/meta-pipewire/meta-agl-demo
# In an AGL build these would get included via local.conf includes
# added by aglsetup.sh
require conf/include/agl-appfw-smack.inc
require conf/include/agl-pipewire.inc
require conf/include/agl-demo.inc

# Need to disable Pulseaudio to avoid conflicting with PipeWire
DISTRO_FEATURES_remove = "pulseaudio"
DISTRO_FEATURES_BACKFILL_CONSIDERED_append = " pulseaudio"

# Override default agl-driver user ID to avoid conflicts
# NOTE: Must be less than 2048 to avoid issues with nss-localuser
#       mechanism used by the application framework
LOGIN_USER = "2001"
