require conf/distro/include/auto-common.inc

DISTRO_NAME = "Auto Gvm VirtIO"

PRODUCT = "${MACHINE}"

DISTRO_FEATURES:append = " \
    qti-adsp \
    qti-cdsp \
    qti-cdsp1 \
    qti-core \
    qti-data \
    qti-extra \
    qti-tools \
    qti-security \
    qti-avb \
    qti-virtio \
    ab-boot-support \
"
BBMASK += "meta-qti-bsp/meta-qti-distro/recipes-core/images/machine-image-initramfs.bb"
BBMASK += "meta-qti-bsp-prop/meta-qti-headless-prop/recipes-security/mink/mink.bb"
BBMASK += "meta-qti-bsp/meta-qti-headless/recipes-kernel/linux-msm/linux-msm_6.1.bb"
BBMASK += "meta-qti-bsp/meta-qti-headless/recipes-kernel/toolchain/kernel-toolchain-native_5.15.bb"
BBMASK += "meta-qti-bsp-prop/meta-qti-headless-prop/recipes-kernel/kernel-devicetree/kernel-devicetree.bb"

# Switch package format to rpm for GVM
PACKAGE_CLASSES = "package_rpm"
