require conf/distro/include/auto-common.inc

DISTRO_NAME = "auto gvm"

DISTRO_FEATURES_append= " q-hypervisor"

DISTRO_FEATURES_append = " \
    qti-audio \
    qti-camera \
    qti-core \
    qti-data \
    qti-display \
    qti-extra \
    qti-graphics \
    qti-multimedia \
    qti-security \
    qti-vnw \
    qti-wlan \
    qti-tools \
"
