require conf/distro/include/auto-common.inc

DISTRO_NAME = "auto gvm headless"

PRODUCT = "${MACHINE}-headless"
PRODUCT:gvm-gen4-5 = "gvm-gen4-5-hl"
PRODUCT:quin-gvm-gen4-5 = "gvm-gen4-5-hl"
PRODUCT:quin-tgvm-gen4-5 = "quin-tgvm-gen4-5-hl"

DEPLOY_NAME_BASE:gvm-gen4-5 = "${PRODUCT}"
DEPLOY_NAME_BASE:quin-gvm-gen4-5 = "${PRODUCT}"

BBMASK:quin-tgvm-gen4 += "meta-qti-bsp/meta-qti-distro/recipes-core/images/machine-image-initramfs.bb"
BBMASK:quin-tgvm-gen4 += "meta-qti-bsp/meta-qti-headless/recipes-kernel/linux-msm/linux-msm_6.12.bb"
BBMASK:quin-tgvm-gen4 += "meta-qti-bsp/meta-qti-headless/recipes-kernel/linux-msm/linux-msm-headers_6.12.bb"
BBMASK:quin-tgvm-gen4 += "meta-qti-bsp/meta-qti-headless/recipes-security/securemsm-devicetree/securemsm-devicetree.bb"
BBMASK:quin-tgvm-gen4 += "meta-qti-bsp-prop/meta-qti-headless-prop/recipes-security/mink/mink.bb"
BBMASK:quin-tgvm-gen4-5 += "meta-qti-bsp/meta-qti-distro/recipes-core/images/machine-image-initramfs.bb"
BBMASK:quin-tgvm-gen4-5 += "meta-qti-bsp/meta-qti-headless/recipes-kernel/linux-msm/linux-msm_6.1.bb"
BBMASK:quin-tgvm-gen4-5 += "meta-qti-bsp/meta-qti-headless/recipes-kernel/toolchain/kernel-toolchain-native_5.15.bb"
BBMASK:quin-tgvm-gen4-5 += "meta-qti-bsp-prop/meta-qti-headless-prop/recipes-kernel/kernel-devicetree/kernel-devicetree.bb"

DISTRO_FEATURES:remove = " wifi"
DISTRO_FEATURES:append:quin-tgvm-gen4 = " selinux"
DISTRO_FEATURES_NATIVE:append:quin-tgvm-gen4 = " selinux"

DISTRO_FEATURES:append = " \
    qti-core \
    qti-data \
    qti-extra \
    qti-graphics \
    qti-hypervisor \
    qti-ml \
    qti-security \
    qti-avb \
    qti-fde \
    qti-tools \
"

# Preferred refpolicy
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-targeted"
DEFAULT_ENFORCING = "enforcing"

DISTRO_FEATURES:remove:gvm-gen4-5 = " \
    qti-extra \
    qti-graphics \
    qti-ml \
    qti-bluetooth \
    qti-fde \
"

DISTRO_FEATURES:remove:quin-gvm-gen4-5 = " \
    qti-extra \
    qti-graphics \
    qti-ml \
    qti-bluetooth \
    qti-fde \
"

DISTRO_FEATURES:remove:quin-tgvm-gen4-5 = " \
    qti-fde \
"
