require conf/distro/include/auto-common.inc

DISTRO_NAME = "auto gvm"

DISTRO_FEATURES:append = " \
    qti-adsp \
    qti-audio \
    qti-audio-ar \
    qti-camera \
    qti-cdsp \
    qti-core \
    qti-data \
    qti-display \
    qti-extra \
    qti-graphics \
    qti-ml \
    qti-multimedia \
    qti-security \
    qti-vnw \
    qti-tools \
    qti-avb \
    qti-fde \
"

DISTRO_FEATURES:remove:quin-gvm-gen4-2 = "\
    qti-audio \
    qti-ml \
    qti-vnw \
"

DISTRO_FEATURES:remove:qtiquingvm8295 = "\
    qti-audio \
    qti-ml \
"

DISTRO_FEATURES:remove:quin-gvm-lemans = "\
    qti-audio \
    qti-ml \
    qti-vnw \
"

DISTRO_FEATURES:remove:quin-gvm-gen4-2 = "early-eth ipa3 wifi"
DISTRO_FEATURES:remove:quin-gvm-lemans = "early-eth ipa3 qti-wlan wifi"
DISTRO_FEATURES:remove:qtiquingvm8295 = "early-eth ipa3 wifi"
