require ${QTI_METAPATH_DISTRO}/conf/distro/auto.conf

DISTRO_FEATURES_append = " alsa qti-avb selinux"

PRODUCT = "${MACHINE}agl"

#
# For compatibility with meta-agl-core:
#

# Enable meta-agl-core bbappends
AGL_FEATURES = "aglcore"

# Currently required to avoid failures in anonymous python logic
# in agl-image-minimal.inc
AGL_DEFAULT_IMAGE_FSTYPES = "ext4"
AGL_EXTRA_IMAGE_FSTYPES = ""

# Required for potentially building RBA or agl-compositor
AGL_BRANCH = "koi"

# Specify the weston package as the provider of AGL's "weston-ini"
# runtime dependency to quiet warnings.
PREFERRED_RPROVIDER_weston-ini = "weston"

# Prefer refpolicy
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mcs"
PREFERRED_VERSION_refpolicy-mcs = "2.20190201"
DEFAULT_ENFORCING = "enforcing"

# Enable connman to have network come up automatically for demo
# development
VIRTUAL-RUNTIME_net_manager = "connman"

# Needed to allow building gdb and installing gdbserver into images
# for demo development
WHITELIST_GPL-3.0 += "gdb gdbserver"

# Prevent weston.ini in weston-init to be removed
BBMASK += "meta-agl/meta-agl-core/recipes-graphics/wayland/weston-init.bbappend"
# Use libselinux.bb in meta-selinux instead of the one in external
BBMASK += "meta-qti-bsp/meta-qti-base/recipes-aosp/libselinux/libselinux_git.bb"
