#This DISTRO conf use for factory test.

require conf/distro/auto.conf

DISTRO_NAME = "auto-slt"

DISTRO_FEATURES:append = " \
    qti-slt \
"
# set sa8797-slt as default product in auto-slt distro
PRODUCT = "${MACHINE}-slt"
