require conf/distro/auto.conf

DISTRO_FEATURES:append = " qti-lxc qti-avb"

# Disable qti-lxc qti-avb on LeMans as features are not ready
DISTRO_FEATURES:remove:lemans = "qti-avb"

# Disable qti-avb on sa81x5(kernel-5.15) as features are not ready
DISTRO_FEATURES:remove:sa81x5 = "qti-avb"

PRODUCT = "${MACHINE}lxc"
