require conf/distro/include/auto-common.inc

DISTRO_NAME = "auto gvm headless"

PRODUCT = "${MACHINE}-headless"
PRODUCT:quin-gvm-gen4-5 = "gvm-gen4-5-hl"

DEPLOY_NAME_BASE:quin-gvm-gen4-5 = "${PRODUCT}"

BBMASK:quin-tgvm-gen4 += "meta-qti-bsp/meta-qti-distro/recipes-core/images/machine-image-initramfs.bb"

DISTRO_FEATURES:append = " qti-hypervisor"
DISTRO_FEATURES:remove = " wifi"
DISTRO_FEATURES:append:quin-tgvm-gen4 = " selinux"
DISTRO_FEATURES_NATIVE:append:quin-tgvm-gen4 = " selinux"

DISTRO_FEATURES:append = " \
    qti-core \
    qti-data \
    qti-extra \
    qti-graphics \
    qti-ml \
    qti-security \
    qti-avb \
    qti-fde \
"

# Preferred refpolicy
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-targeted"
DEFAULT_ENFORCING = "enforcing"

DISTRO_FEATURES:remove:quin-gvm-gen4-5 = " \
    qti-extra \
    qti-graphics \
    qti-ml \
    qti-bluetooth \
    qti-fde \
"
