require conf/distro/include/auto-common.inc

DISTRO_NAME = "auto"

DISTRO_FEATURES:append = " \
    qti-adsp \
    qti-audio \
    qti-bluetooth \
    qti-audio-ar \
    qti-camera \
    qti-cdsp \
    qti-core \
    qti-data \
    qti-display \
    qti-extra \
    qti-graphics \
    qti-ml \
    qti-multimedia \
    qti-security \
    qti-tools \
    qti-vnw \
    qti-location \
    qti-avb \
    ab-boot-support \
"

# Disable it on on sa81x5(kernel-5.15) as features are not ready
DISTRO_FEATURES:remove = "\
    qti-ml \
    qti-security \
    qti-vnw \
    qti-location \
"
DISTRO_FEATURES:remove = "early-eth ipa3"

# Disable qti-avb on minimal as the feature not need
DISTRO_FEATURES:remove:pn-core-image-minimal = "qti-avb"
