require conf/distro/auto.conf

DISTRO_FEATURES:append = " qti-lxc qti-avb"
DISTRO_FEATURES:remove:lemans = " qti-lxc"

DISTRO_FEATURES:append:sa81x5 = " selinux"
DISTRO_FEATURES_NATIVE:append:sa81x5 = " selinux"

PRODUCT = "${MACHINE}lxc"

# Targets with selinux enabled should use libseilnux in meta-selinux, others stay the way it was.
BBMASK:sa81x5 += "meta-qti-bsp/meta-qti-base/recipes-aosp/libselinux/libselinux_git.bb"

# Prefer refpolicy
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mcs"
DEFAULT_ENFORCING = "permissive"
