#@TYPE: Machine
#@NAME: msm8996

#@DESCRIPTION: Machine configuration for msm systems.

MACHINE_EXTRA_RRECOMMENDS = " kernel-modules kernel-devicetree"

require conf/machine/include/8x96autogvmga.inc

IMAGE_FSTYPES += "tar.bz2 ext4"

PREFERRED_PROVIDER_virtual/kernel = "linux-gvm-4.4"

#
# Graphics driver essentials
#
PREFERRED_PROVIDER_virtual/wayland-egl  = "adreno"
PREFERRED_PROVIDER_virtual/egl          = "adreno"
PREFERRED_PROVIDER_virtual/libgles1     = "adreno"
PREFERRED_PROVIDER_virtual/libgles2     = "adreno"

SERIAL_CONSOLE ?= "115200 hvc0"

KERNEL_IMAGETYPE ?= "Image"
KERNEL_DEVICETREE ?= "qcom/vplatform-lfv-msm8996.dtb"
KERNEL_DTS_NAME = "vplatform-lfv-msm8996"
KERNEL_BASE ?= "0x80000000"
#TODO: dynamically set root device based on board version
KERNEL_CMDLINE ?= "console=hvc0,115200"

KERNEL_DEFCONFIG = "msm-auto-gvm_defconfig"
KERNEL_PERF_DEFCONFIG = "msm-auto-gvm-perf_defconfig"
KERNEL_PATCH ?= ""
OVERRIDES .= "${@':kernelpatchok' if '${KERNEL_PATCH}' != 'conflict' else ''}"

# Sizes for EXT4 (in bytes)
USERDATA_SIZE_EXT4 = "2000000000"
CACHE_SIZE_EXT4 = "80000000"

DISTRO_FEATURES_append = " persist-image"

INCOMPATIBLE_LICENSE = "GPL-3.0 LGPL-3.0 AGPL-3.0 GPLv3+ LGPLv2.1+"

BBMASK_append = "|meta-qti-bsp/recipes-devtools/log4cxx/log4cxx_svn.bbappend"
BBMASK_append = "|meta-qti-bsp/recipes-devtools/yaml-cpp/yaml-cpp_%.bbappend"
BBMASK_append = "|meta-qti-bsp/recipes-ros/console-bridge/console-bridge_%.bbappend"
BBMASK_append = "|meta-qti-bsp/recipes-ros/pluginlib/pluginlib_1.10.%.bbappend"
