#@TYPE: Machine
#@NAME: msm8996

#@DESCRIPTION: Machine configuration for msm systems.

MACHINE_EXTRA_RRECOMMENDS = " kernel-modules kernel-devicetree"

require conf/machine/include/8x96autogvmquin.inc

IMAGE_FSTYPES += "tar.bz2 ext4"

PREFERRED_PROVIDER_virtual/kernel = "linux-gvm"

#
# Graphics driver essentials
#
PREFERRED_PROVIDER_virtual/wayland-egl  = "adreno"
PREFERRED_PROVIDER_virtual/egl          = "adreno"
PREFERRED_PROVIDER_virtual/libgles1     = "adreno"
PREFERRED_PROVIDER_virtual/libgles2     = "adreno"

SERIAL_CONSOLE ?= "115200 ttyAMA0"

KERNEL_IMAGETYPE ?= "Image"
KERNEL_DEVICETREE ?= "qcom/vplatform-lfv-msm8996.dtb"
KERNEL_DTS_NAME = "vplatform-lfv-msm8996"
KERNEL_BASE ?= "0x80000000"
#TODO: dynamically set root device based on board version
KERNEL_CMDLINE ?= "console=ttyAMA0,115200"

KERNEL_DEFCONFIG = "msm-auto-gvm_defconfig"
KERNEL_PERF_DEFCONFIG = "msm-auto-gvm-perf_defconfig"

# Sizes for EXT4 (in bytes)
USERDATA_SIZE_EXT4 = "2000000000"
CACHE_SIZE_EXT4 = "80000000"

DISTRO_FEATURES_append = " persist-image"

BBMASK_append = "|meta-qti-bsp/recipes-connectivity/ofono/ofono_%.bbappend"
