#@TYPE: Machine
#@NAME: msm8996

#@DESCRIPTION: Machine configuration for msm systems.

require conf/machine/include/auto-common.inc
#require conf/machine/include/8x96autogvmquintcu.inc

MACHINE_EXTRA_RRECOMMENDS = " kernel-modules kernel-devicetree"
IMAGE_FSTYPES += "tar.bz2 ext4"

PREFERRED_PROVIDER_virtual/kernel = "linux-gvm-4.4"



SERIAL_CONSOLE ?= "115200 ttyAMA0"

KERNEL_IMAGETYPE ?= "Image"
KERNEL_DEVICETREE ?= "qcom/vplatform-lfv-msm8996.dtb"
KERNEL_DTS_NAME = "vplatform-lfv-msm8996"
KERNEL_BASE ?= "0x80000000"
#TODO: dynamically set root device based on board version
KERNEL_CMDLINE ?= "console=ttyAMA0,115200"

KERNEL_DEFCONFIG = "msm-auto-gvm_defconfig"
KERNEL_PERF_DEFCONFIG = "msm-auto-gvm-perf_defconfig"

# Sizes for EXT4 (in bytes)
USERDATA_SIZE_EXT4 = "2000000000"
CACHE_SIZE_EXT4 = "80000000"

DISTRO_FEATURES_append = " persist-image"
