#@TYPE: Machine
#@NAME: msm8996

#@DESCRIPTION: Machine configuration for msm systems


MACHINE_EXTRA_RRECOMMENDS = " kernel-modules kernel-devicetree"

require conf/machine/include/arm/arch-armv8.inc

IMAGE_FSTYPES += "tar.bz2 ext4"

PREFERRED_PROVIDER_virtual/kernel = "linux-yocto-msm8996"

MACHINE_SOC_NAME = "msm8996"

#
# Graphics driver essentials
#
PREFERRED_PROVIDER_virtual/wayland-egl  = "adreno"
PREFERRED_PROVIDER_virtual/egl          = "adreno"
PREFERRED_PROVIDER_virtual/libgles1     = "adreno"
PREFERRED_PROVIDER_virtual/libgles2     = "adreno"

SERIAL_CONSOLE ?= "115200 ttyHSL0"

KERNEL_IMAGETYPE ?= "Image"
KERNEL_DEVICETREE ?= "qcom/apq8096pro-auto-cdp.dtb qcom/apq8096pro-v1.1-auto-adp.dtb qcom/apq8096pro-v1.1-auto-adp-lite.dtb qcom/apq8096pro-v1.1-auto-cdp.dtb qcom/apq8096-v2-auto-dragonboard.dtb qcom/apq8096-v3-auto-adp.dtb qcom/apq8096-v3-auto-cdp.dtb qcom/apq8096-v3-auto-dragonboard.dtb qcom/msm8996pro-auto-adp.dtb qcom/msm8996pro-auto-adp-lite.dtb qcom/msm8996pro-auto-cdp.dtb qcom/msm8996pro-v1.1-auto-cdp.dtb qcom/msm8996-v3-auto-adp.dtb qcom/msm8996-v3-auto-cdp.dtb"
KERNEL_BASE ?= "0x80000000"
#TODO: dynamically set root device based on board version
KERNEL_CMDLINE ?= "console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 cma=16M@0-0xffffffff rootwait rootfstype=ext4 root=/dev/mmcblk0p18"
RECOVERY_KERNEL_CMDLINE ?= "console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 cma=16M@0-0xffffffff rootfstype=ramfs root=/dev/ram0 rdinit=/sbin/init"

# Sizes for EXT4 (in bytes)
USERDATA_SIZE_EXT4 = "2000000000"
CACHE_SIZE_EXT4 = "80000000"

DISTRO_FEATURES_append = " persist-image"
KERNEL_DEFCONFIG = "msm-auto_defconfig"
KERNEL_PERF_DEFCONFIG = "msm-auto-perf_defconfig"
