#@TYPE: Machine
#@NAME: AR-Gen1
#@DESCRIPTION: Machine configuration for Neo

require conf/machine/sxrneo.conf

PREFERRED_VERSION_linux-msm = "6.1"
PREFERRED_VERSION_linux-msm-headers = "6.1"
PREFERRED_VERSION_mod-signing-keys = "6.1"
PREFERRED_VERSION_kernel-toolchain-native = "6.1.32bit"
PREFERRED_VERSION_mkbootimg-gki = "6.1"
PREFERRED_VERSION_mkbootimg-gki-native = "6.1"
PREFERRED_VERSION_msm-bus = "6.1"
PREFERRED_VERSION_gki-kernel-modules = "6.1"
PREFERRED_VERSION_merge-dtbs-gki-native = "6.1"
PREFERRED_VERSION_displaydlkm = "6.1"
PREFERRED_VERSION_displaydevicetree = "6.1"
PREFERRED_VERSION_securemsmdlkm = "6.1"
PREFERRED_VERSION_mmrm-kernel = "6.1"
PREFERRED_VERSION_video-kernel = "6.1"
PREFERRED_VERSION_video-devicetree = "6.1"
PREFERRED_VERSION_audiodlkm = "6.1"
PREFERRED_VERSION_audiodevicetree= "6.1"
PREFERRED_VERSION_fastrpc-kernel = "6.1"
PREFERRED_VERSION_eva-kernel = "6.1"
PREFERRED_VERSION_qti-eva-kernel-headers = "6.1"
PREFERRED_VERSION_synx-kernel = "6.1"
PREFERRED_VERSION_wlan-platform = "6.1"
PREFERRED_VERSION_qcacld32-ar-sg1 = "6.1"
PREFERRED_VERSION_eva-devicetree = "6.1"
PREFERRED_VERSION_synx-kernel-header = "6.1"
PREFERRED_VERSION_graphicsdevicetree = "6.1"
PREFERRED_VERSION_graphicsdlkm = "6.1"
PREFERRED_VERSION_cameradlkm = "6.1"
PREFERRED_VERSION_cameradtb = "6.1"
PREFERRED_VERSION_edk2 = "6.1"

USE_CLANG = "True"

KERNEL_TYPE = "dist"

KERNEL_DTB_NAMES += " \
    neo_la.dtb \
    neo_luna-v2.dtb \
"

PREFERRED_PROVIDER_virtual/kernel = "linux-msm-src"
PREFERRED_PROVIDER_linux-msm-headers = "linux-msm-headers-src"
PREFERRED_PROVIDER_fastrpc-kernel = "fastrpc-kernel-src"

KERNEL_CMD_PARAMS  += "console=ttyMSM0,115200,n8"
MACHINE_USES_KERNEL_PREBUILTS = "False"

KERNEL_DEFCONFIG = "msm-kernel-neo_le-perf_defconfig"
KERNEL_DEFCONFIG:qti-distro-debug = "msm-kernel-neo_le-debug_defconfig"
KERNEL_PLATFORM_PATH = "${WORKSPACE}/kernel-6.1/kernel_platform"
#KERNEL_PREBUILT_PATH = "${WORKSPACE}/kernel-6.1/out/${KERNEL_DEFCONFIG}"
KERNEL_MODULES_LIST = "modules.list.msm.neo-le"
KERNEL_CONFIG     = "generic_sxr_defconfig"
KERNEL_CONFIG:qti-distro-debug = "generic_sxr_defconfig"

MACHINE_FEATURES:remove = "qti-abc-boot"
MACHINE_FEATURES += "qti-ab-boot qti-audio"
MACHINE_FEATURES += "qti-crypto qti-smmu-proxy"
