#@TYPE: Machine
#@NAME: AR-Gen1
#@DESCRIPTION: Machine configuration for Neo

require conf/machine/include/neo.inc

KERNEL_IMAGETYPE   = "Image"

MACHINE_SUPPORTS_DTBO = "True"
KERNEL_DTB_NAMES   = " \
    neo.dtb \
    neo_la.dtb \
    neo_luna-v2.dtb \
"
MACHINE_USES_KERNEL_PREBUILTS = "False"

KERNEL_DEFCONFIG = "msm-kernel-neo_le-perf_defconfig"
KERNEL_DEFCONFIG:qti-distro-debug = "msm-kernel-neo_le-debug_defconfig"

#Various kernel directories
KERNEL_PLATFORM_PATH = "${WORKSPACE}/kernel-6.1/kernel_platform"

KERNEL_MODULES_LIST = "modules.list.msm.neo-le"

KERNEL_BASE        = "0x80000000"

KERNEL_CONFIG     ?= "generic_sxr_defconfig"

CONSOLE_PARAM     ?= ""
CONSOLE_PARAM:qti-distro-debug ?= "earlycon msm_geni_serial.con_enabled=1 earlycon=msm_geni_serial,0x00A94000"
CONSOLE_PARAM:qti-distro-perf ?= "                                        "

KERNEL_CMD_PARAMS  = "${CONSOLE_PARAM} verity=enabled"

#Remove verity=enabled from kernel cmd line, when dm-verity is disabled.
KERNEL_CMD_PARAMS:remove = "${@bb.utils.contains('MACHINE_FEATURES', 'dm-verity-none', 'verity=enabled', '', d)}"

SERIAL_CONSOLES    ?= ""
SERIAL_CONSOLES:qti-distro-debug = "115200;ttyMSM0"

# bootloader configuration
EXTRA_IMAGEDEPENDS += "edk2"

# Default USB composition to be picked
USBCOMPOSITION = "9060"

# Conf with partition entries required for machine.
MACHINE_PARTITION_CONF = "sxrneo-partition.conf"

# filesystem configurations to be applied on image.
MACHINE_FSCONFIG_CONF = "neo-fsconfig.conf"

# init ramdisk image to be used for first stage boot.
INITRAMFS_IMAGE = "qti-ramdisk-image"
INITRAMFS_FSTYPES = "cpio.lz4"
VENDOR_INITRAMFS_IMAGE = "qti-vendor-ramdisk-image"

# File indicating firmware residing places on device.
MACHINE_FILESMAP_CONF = "neo-filesmap"

# Enable qti-ab-boot feature with OTA package
GENERATE_AB_OTA_PACKAGE = "1"

#do not redirect system and journal logs to console
NO_SYS_JOURNAL_LOGS_TO_CONSOLE = "1"

#Flag to disable usbd.service
USB_PERIPHERAL_ONLY_MODE = "True"

USE_CLANG = "True"

MACHINE_FEATURES += "drm emmc-boot qti-adsp qti-audio qti-cdsp qti-eva qti-camera qti-crypto \
                     qti-ab-boot qti-sensors qti-audio qti-tzlog smcinvoke qti-bluetooth \
                     qti-wifi qwesd file-based-encryption qti-codec2 qti-smciqseecomd \
                     dm-verity-initramfs-v2 qti-smmu-proxy"


PREFERRED_VERSION_linux-msm = "6.1"
PREFERRED_VERSION_linux-msm-headers = "6.1"
PREFERRED_VERSION_mod-signing-keys = "6.1"
PREFERRED_VERSION_kernel-toolchain-native = "6.1.32bit"
PREFERRED_VERSION_mkbootimg-gki = "6.1"
PREFERRED_VERSION_mkbootimg-gki-native = "6.1"
PREFERRED_VERSION_msm-bus = "6.1"
PREFERRED_VERSION_gki-kernel-modules = "6.1"
PREFERRED_VERSION_merge-dtbs-gki-native = "6.1"
PREFERRED_VERSION_displaydlkm = "6.1"
PREFERRED_VERSION_displaydevicetree = "6.1"
PREFERRED_VERSION_securemsmdlkm = "6.1"
PREFERRED_VERSION_mmrm-kernel = "6.1"
PREFERRED_VERSION_video-kernel = "6.1"
PREFERRED_VERSION_video-devicetree = "6.1"
PREFERRED_VERSION_audiodlkm = "6.1"
PREFERRED_VERSION_audiodevicetree= "6.1"
PREFERRED_VERSION_fastrpc-kernel = "6.1"
PREFERRED_VERSION_eva-kernel = "6.1"
PREFERRED_VERSION_qti-eva-kernel-headers = "6.1"
PREFERRED_VERSION_synx-kernel = "6.1"
PREFERRED_VERSION_wlan-platform = "6.1"
PREFERRED_VERSION_qcacld32-ar-sg1 = "6.1"
PREFERRED_VERSION_eva-devicetree = "6.1"
PREFERRED_VERSION_synx-kernel-header = "6.1"
PREFERRED_VERSION_graphicsdevicetree = "6.1"
PREFERRED_VERSION_graphicsdlkm = "6.1"
PREFERRED_VERSION_cameradlkm = "6.1"
PREFERRED_VERSION_cameradtb = "6.1"
PREFERRED_VERSION_edk2 = "6.1"

PREFERRED_PROVIDER_virtual/kernel = "linux-msm-src"
PREFERRED_PROVIDER_linux-msm-headers = "linux-msm-headers-src"
PREFERRED_PROVIDER_fastrpc-kernel = "fastrpc-kernel-src"

