#@TYPE: Machine
#@NAME: ECHO-AB
#@DESCRIPTION: Machine configuration for Amboseli-RDKB-AB
BASEMACHINE ?= "echo"

MACHINE_FEATURES += "qti-ab-boot qti-recoveryinfo"

MACHINE_FEATURES_remove += "qti-recovery"

MACHINE_PARTITION_CONF = "echo-ab-partition.conf"

GENERATE_AB_OTA_PACKAGE = "1"

MACHINE_SUPPORTS_A_SUFFIX = "False"
