#@TYPE: Machine
#@NAME: ECHO
#@DESCRIPTION: Machine configuration for Amboseli-RDKB with verity

require ${COREBASE}/meta-qti-bsp/conf/machine/echo-base.conf

MACHINE_FEATURES += "dm-verity-initramfs-v3"

DISTRO_FEATURES += "dm-verity"

KERNEL_CMD_PARAMS += "verity=enabled"
