#@TYPE: Machine
#@NAME: ECHO-AB
#@DESCRIPTION: Machine configuration for Amboseli-RKDB AB

require ${COREBASE}/meta-qti-bsp/conf/machine/echo.conf

require ${COREBASE}/meta-qti-bsp/conf/machine/echo-ab-common.conf
