#@TYPE: Machine
#@NAME: ECHO-AB
#@DESCRIPTION: Machine configuration for Amboseli-RDKB-AB

require ${COREBASE}/meta-qti-bsp/conf/machine/echo-verity.conf

require ${COREBASE}/meta-qti-bsp/conf/machine/echo-ab-common.conf
