#@TYPE: Machine
#@NAME: SDXNIGHTJAR
#@DESCRIPTION: Machine configuration for QTI SDXNIGHTJAR MTP

require conf/machine/include/sdxnightjar.inc

PREFERRED_PROVIDER_virtual/kernel ?= "linux-msm"
PREFERRED_VERSION_linux-msm ?= "5.4"

KERNEL_IMAGETYPE = "zImage-dtb"
KERNEL_DTB_NAMES = "vendor/qcom/sdxnightjar-mtp.dtb"
KERNEL_BASE = "0x80000000"
KERNEL_TAGS_OFFSET = "0x82000000"
KERNEL_CONFIG = "${@['vendor/sdxnightjar_defconfig', 'vendor/sdxnightjar-debug_defconfig'][d.getVar('VARIANT', True) == ('' or 'debug')]}"
KERNEL_CMD_PARAMS = "noinitrd ro console=ttyMSM0,115200,n8 androidboot.hardware=qcom ehci-hcd.park=3 msm_rtb.filter=0x37 lpm_levels.sleep_disabled=1 earlycon=msm_serial_dm,0x78b1000 firmware_class.path=/firmware/image"

# Remove console related parameters for non-debug builds.
KERNEL_CMD_PARAMS_remove = "${@bb.utils.contains_any('VARIANT', 'perf user', 'console=ttyMSM0,115200,n8', '', d)}"
KERNEL_CMD_PARAMS_remove = "${@bb.utils.contains_any('VARIANT', 'perf user', 'earlycon=msm_serial_dm,0x78b1000', '', d)}"

GCCVERSION = "8.2%"
LLVM_VERSION = "6.0"

#Enable audio kernel
DISTRO_FEATURES += "audiodlkm audio-dlkm"

#Uncomment the below line to enable recovery upgrade for nand devices
#DISTRO_FEATURES += "nand-recovery-upgrade"

#Uncomment the below line to enable OTA package verification feature
DISTRO_FEATURES_append += " ota-package-verification"
MACHINE_MNT_POINTS = "/firmware /persist /cache"

#Enable Recovery image generation
RECOVERY_IMAGE = "1"

DISTRO_FEATURES_append += " selinux"
DISTRO_FEATURES_FILTER_NATIVE += " selinux"
DEFAULT_ENFORCING = "enforcing"
