#@TYPE: Machine
#@NAME: SDXPINN-AB
#@DESCRIPTION: Machine configuration for SDXPINN-AB
BASEMACHINE ?= "sdxpinn"

require ${COREBASE}/meta-qti-bsp/conf/machine/sdxpinn.conf

MACHINE_FEATURES += "qti-ab-boot qti-recoveryinfo"

GENERATE_AB_OTA_PACKAGE = "1"

