#@TYPE: Machine
#@NAME: SDXPINN-AB
#@DESCRIPTION: Machine configuration for SDXPINN-AB
BASEMACHINE ?= "sdxpinn"

require ${COREBASE}/meta-qti-bsp/conf/machine/sdxpinn.conf

MACHINE_FEATURES += "qti-ab-boot qti-recoveryinfo"

MACHINE_FEATURES_remove += "qti-recovery"

MACHINE_PARTITION_CONF = "sdxpinn-ab-partition.conf"

GENERATE_AB_OTA_PACKAGE = "1"
