#@TYPE: Machine
#@NAME: TRUSTEDVM-MALABAR
#@DESCRIPTION: Machine configuration for QTI MTP with TRUSTEDVM

require conf/machine/trustedvm-v4.conf

#### dtb ####
KERNEL_DTB_NAMES = "malabar-vm-*.dtb malabar-oemvm-*.dtb"
