#@TYPE: Machine
#@NAME: vienna
#@DESCRIPTION: Machine configuration for QTI HDK with vienna
BASEMACHINE ?= "vienna"
require conf/machine/include/basemachine.inc

DEFAULTTUNE ?= "aarch64"
include conf/machine/include/arm/arch-armv8a.inc

require recipes-kernel/linux-msm/msm-common.inc

PREFERRED_VERSION_synx-kernel ?= "1.0"
PREFERRED_VERSION_securemsmdlkm ?= "1.1"
PREFERRED_VERSION_touchdlkm = "1.0"
PREFERRED_VERSION_mod-blacklist ?= "2.0"

# clang version for kernel toolchain 6.12
CLANG_VERSION = "r536225"

KERNEL_MODULES_LIST = "modules-lists/modules.list.msm.vienna-le"
KERNEL_MODULES_BLACKLIST = "\
    modules.vendor_blocklist.msm.vienna-le \
    modules.systemdlkm_blocklist.msm.vienna-le \
"

# Check for soc-repo or gki_kernel

#extra module blacklist
EXTRA_BLACKLIST_MOD ?= ""

HOSTTOOLS += "rsync"

KERNEL_CONFIG  ?= "build.config.msm.vienna.le"
KERNEL_BUILD_CONFIG = "soc-repo/${KERNEL_CONFIG}"
KERNEL_IS_SOC_REPO = "True"

#### dtb ####
KERNEL_DTB_NAMES = "vienna.dtb viennap.dtb"

#### boot.img ####
KERNEL_IMAGETYPE = "Image"
KERNEL_BASE = "0x80000000"
KERNEL_TAGS_OFFSET = "0x80000000"
BOOT_HEADER_VERSION = "2"

#### systemd ####
SERIAL_CONSOLE ?= "115200;ttyMSM0"

#### cmdline ####
CONSOLE_PARAM:qti-distro-perf  = ""
CONSOLE_PARAM:qti-distro-debug = ""
CONSOLE_PARAM += " lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=noforce kpti=off cgroup.memory=nokmem,nosocket loop.max_part=7 qcom_geni_serial.con_enabled=0"
HIBERNATION_PARAMS = "hibernate=nocompress"
KERNEL_CMD_PARAMS = "${CONSOLE_PARAM}"

# TODO: Temporary change to override BB_SIGNATURE_HANDLER set in local.conf.
# Other machines are already supporting OEEquivHash as hashing signature.
# Fix build issues observed in this machine and remove this override.
BB_SIGNATURE_HANDLER = "OEBasicHash"

#QSEEComCompat and QSEECom are mutually exlusive and QSEEComCompat depends on  smcinvoke
#lv-build builds the required listernes , le_qseecom enables qseecomd
MACHINE_FEATURES += "dm-verity-none"

MACHINE_MNT_POINTS = " \
	/persist \
	/firmware \
	/vendor/bt_firmware \
	/dsp \
	/overlay \
"

SYSTEM_SIZE_EXT4   ?= "4294967296"
PERSIST_SIZE_EXT4 ?= "7MiB"
# Define userdata dir, size to be used
USERDATA_DIR = "${@bb.utils.contains('MACHINE_MNT_POINTS', '/overlay', 'overlay', 'data', d)}"
USERDATA_SIZE ?= "8589934592"

# Formats of root filesystem images
IMAGE_FSTYPES += "ext4"
MACHINE_SUPPORTS_PDMAPPER = "True"
MACHINE_SUPPORTS_ANDROID_PROPERTIES = "True"
MACHINE_SUPPORTS_DISPLAY = "False"
MACHINE_FSCONFIG_CONF = "vienna-fsconfig.conf"
MACHINE_SUPPORTS_SSR = "True"

USBCOMPOSITION = "901D"

# Partition conf
MACHINE_PARTITION_CONF = "vienna-partition.conf"

# File indicating firmware residing places on device.
MACHINE_FILESMAP_CONF = "vienna-filesmap"

### MACHINE_FEATURES ###
MACHINE_FEATURES += "qti-ab-boot qti-adsp qti-cdsp fastrpc qti-tzlog qti-crypto qti-smmu-proxy qti-security qti-audio smcinvoke qti-smciqseecomd qseecompat qti-rpmb file-based-encryption qti-tmecom qwesd ota-whole-file-sign"
# := freezes value at parse time so native recipes (which reset MACHINE_FEATURES) still see this feature.
OTA_WHOLE_FILE_SIGN := "${@bb.utils.contains('MACHINE_FEATURES', 'ota-whole-file-sign', 'true', 'false', d)}"

# On msm-5.4 or above ufs driver supports BSG Device.
UFS_BSG_DEV_USAGE = "True"

DISTRO_FEATURES:remove = "virtualization ros2 qirp-sdk qti-ib2c qti-uvc qti-umd-gadget qti-auto-framing-stabilization"

QPERMISSIONS_ENABLE = "1"

# pack for installation of ESDK
COREBASE_FILES:append = " meta-poky"

PACKAGECONFIG:append:pn-chicdk = " nogpu"
