require conf/machine/include/qcs40x.inc

DEFAULTTUNE = "aarch64"

KERNEL_IMAGETYPE = "Image.gz"

LLVM_VERSION = "10.0"

#MACHINE_SUPPORTS_DTBO = "True"
DTBO_DTB_NAMES   = " \
    vendor/qcom/kona.dtb \
    vendor/qcom/kona-v2.dtb \
    vendor/qcom/kona-v2.1.dtb \
"

KERNEL_BASE        = "0x80000000"
KERNEL_TAGS_OFFSET = "0x81900000"
#KERNEL_DTB_NAMES = "${@bb.utils.contains('MACHINE_SUPPORTS_DTBO', 'True', "${DTBO_DTB_NAMES}", "", d)}"

#defconfig to be used for vt-64
KERNEL_CONFIG     ?= "vendor/kona-perf_defconfig"
KERNEL_CONFIG_qti-distro-debug ?= "vendor/kona_defconfig"
#KERNEL_CONFIG ?= "vendor/qcs405-perf_defconfig"
#KERNEL_CONFIG_qti-distro-debug ?= "vendor/qcs405_defconfig"

KERNEL_CMD_PARAMS = "noinitrd ro rootwait console=ttyMSM0,115200,n8 no_console_suspend=1 androidboot.hardware=qcom androidboot.console=ttyMSM0 lpm_levels.sleep_disabled=1 service_locator.enable=1 firmware_class.path=/lib/firmware/updates msm_rtb.filter=0x237"

#list of hardware features that MACHINE is capable of supporting
MACHINE_FEATURES:append = "qti-gpu"

MACHINE_FSCONFIG_CONF = "vt-64-fsconfig.conf"

MACHINE_PARTITION_CONF = "vt-64-partition.conf"

MACHINE_FEATURES += " dm-verity-none"
#require conf/multilib.conf
#MULTILIBS = "multilib:lib32"
#DEFAULTTUNE:virtclass-multilib-lib32 = "armv7ahf-neon"
#TARGET_VENDOR:virtclass-multilib-lib32 = "-oe"

#enable stderror debug for vt devices
PACKAGECONFIG:append:pn-adk-utils = "stderr debug"

# Formats of root filesystem images
IMAGE_FSTYPES = "ext4"
