>mask=5
cmd-db.ko
qcom_hwspinlock.ko
gh_msgq.ko
gh_dbl.ko
gh_rm_drv.ko
smem.ko
:mem_buf_dev.ko
qcom_dma_heaps.ko
debug_symbol.ko
minidump.ko
qcom_va_minidump.ko
qcom_ipc_logging.ko
qcom_aoss.ko
msm_qmp.ko
socinfo.ko
qcom-dload-mode.ko
qcom-reboot-reason.ko
qcom_cpu_vendor_hooks.ko
qcom_scmi_client.ko
qcom_scmi_vendor.ko
gic_intr_routing.ko
cpu_phys_log_map.ko
qcom_llcc_pmu.ko
qcom-pmu-lib.ko
llcc-qcom.ko
dcc_v2.ko
qcom_wdt_core.ko
gh_virt_wdt.ko
rtc-pm8xxx.ko
qcom_logbuf_vendor_hooks.ko
cpu_hotplug.ko  
cpu_phys_log_map.ko
sched-walt.ko
cpucp_fast.ko
qcom_cpucp.ko
