>mask=7
debug-regulator.ko
proxy-consumer.ko
:cmd-db.ko
:msm_qmp.ko
crm-v2.ko
qcom_rpmh.ko
rpmh-regulator.ko
gdsc-regulator.ko
clk-qcom.ko
clk-dummy.ko
clk-rpmh.ko
gcc-kera.ko
gcc-sun.ko
gcc-tuna.ko
dispcc-sun.ko
dispcc-tuna.ko
camcc-kera.ko
camcc-sun.ko
camcc-tuna.ko
cambistmclkcc-sun.ko
cambistmclkcc-tuna.ko
videocc-sun.ko
evacc-sun.ko
tcsrcc-tuna.ko
tcsrcc-sun.ko
qcom-ipcc.ko
