>mask=0
:qcom_rpmh.ko
icc-debug.ko
icc-bcm-voter.ko
icc-rpmh.ko
:dispcc-sun.ko
qnoc-qos.ko
qnoc-kera.ko
qnoc-sun.ko
qnoc-tuna.ko
gpucc-kera.ko
gpucc-sun.ko
gpucc-tuna.ko
gunyah_loader.ko
:qcom_ipc_logging.ko
qrtr.ko
