>mask=0
:clk-qcom.ko
:arm_smmu.ko
:qcom_ipc_logging.ko
:mem_buf.ko
sched-walt.ko
spmi-pmic-arb.ko
qcom-spmi-pmic.ko
qcom_ice.ko
cqhci.ko
sdhci-msm.ko
phy-qcom-ufs.ko
phy-qcom-ufs-qmp-v4-niobe.ko
ufshcd-crypto-qti.ko
ufs-qcom.ko
phy-qcom-ufs-qmp-v4-sun.ko
phy-qcom-ufs-qrbtc-sdm845.ko
sg.ko
@dm_create_tasklet
@wait_rootfs_tasklet
