[Journal]
Storage=volatile
RuntimeMaxUse=1M
RuntimeKeepFree=512K
SystemMaxUse=0
SystemMaxFileSize=0
SystemKeepFree=0

ForwardToSyslog=no
ForwardToKMsg=yes
ForwardToConsole=no
ForwardToWall=no

MaxRetentionSec=30
MaxFileSec=10
RateLimitIntervalSec=5
RateLimitBurst=50
