# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear
[Service]
ImportCredential=
LoadCredential=
SetCredential=

ExecStart=

SELinuxContext=
PrivateDevices=no
PrivateMounts=no
ProtectSystem=no
ProtectHome=no
NoNewPrivileges=no
CapabilityBoundingSet=

ExecStart=/usr/bin/systemd-tmpfiles --prefix=/dev --create --boot