#@TYPE: Machine
#@NAME: quin-tgvm-gen4
#@DESCRIPTION: Machine configuration for QTI QUIN

# Default Image names
BOOTIMAGE_TARGET ?= "${PRODUCT}-boot.img"
PERSISTIMAGE_TARGET ?= "${PRODUCT}-persist.ext4"
USERDATAIMAGE_TARGET ?= "${PRODUCT}-usrfs.ext4"
VBMETAIMAGE_TARGET ?= "${PRODUCT}-vbmeta.img"

# Flag to Enable QPermissions
QPERMISSIONS_ENABLE ?= "0"

include conf/machine/include/tune-cortexa78c.inc

PREFERRED_PROVIDER_mkbootimg-native = "mkbootimg-gki-native"
PREFERRED_PROVIDER_dtc-native = "dtc-gki-native"

PREFERRED_VERSION_linux-msm = "5.15"
PREFERRED_VERSION_linux-msm-headers = "5.15"

KERNEL_ARCH = "autogvm"
KERNEL_VARIANT = "${@bb.utils.contains_any('VARIANT', 'perf user', 'perf_', 'debug_', d)}"
KERNEL_BUILD_CONFIG = "msm-kernel/build.config.msm.${KERNEL_ARCH}.lxc"
KERNEL_IMAGE_HEADER_VERSION = "2"

KERNEL_BASE = "0x80000000"
KERNEL_TAGS_OFFSET = "0x1e00000"
KERNEL_CONFIG = "${@['vendor/autogvm-qgki_defconfig', 'vendor/autogvm-qgki-debug_defconfig'][d.getVar('VARIANT', True) == ('' or 'debug')]}"
KERNEL_CMD_PARAMS = " "
KERNEL_IMAGETYPE = "Image"

USERDATA_SIZE_EXT4 = "1000000000"

SOC_FAMILY ?= "sa-common"
include conf/machine/include/soc-family.inc

PREFERRED_PROVIDER_virtual/kernel = "linux-msm"

# Enables timestamping functionality during building the kernel
KERNEL_DEBUG_TIMESTAMPS = "1"

SERIAL_CONSOLES = "115200;ttyMSM0"

IMAGE_FSTYPES ?= "ext4"
PAGE_SIZE ?= '4096'
IMAGE_ROOTFS_ALIGNMENT = "4096"
EXTRA_IMAGECMD:ext4 += " -b 4096 "

IMAGE_CLASSES += "qimage"

IMAGE_CLASSES += "${@oe.utils.version_less_or_equal('PREFERRED_VERSION_linux-msm', '5.14', '', 'qimage-boot', d)}"

MACHINE_FEATURES += "\
    qti-hypervisor \
"
