SECURITY_CFLAGS_pn-liblog = ""
SECURITY_CFLAGS_pn-ext4-utils = ""
SECURITY_CFLAGS_pn-system-core = ""

SECURITY_CFLAGS_pn-media = "${SECURITY_NO_PIE_CFLAGS}"
SECURITY_LDFLAGS_pn-iptables = "${SECURITY_X_LDFLAGS}"
SECURITY_CFLAGS_pn-gstreamer1.0-qcarcamsrc = "${SECURITY_NO_PIE_CFLAGS}"

SECURITY_CFLAGS_pn-lib32-androidcompat = ""
SECURITY_LDFLAGS_pn-androidcompat = ""

SECURITY_CFLAGS_pn-dbus-c++ = ""
SECURITY_CFLAGS_pn-pugixml = ""
SECURITY_CFLAGS_pn-loc-stub = ""
SECURITY_CFLAGS_pn-loc-pla = ""
SECURITY_CFLAGS_pn-gps-utils = ""
SECURITY_CFLAGS_pn-av-frameworks = ""
SECURITY_CFLAGS_pn-loc-hal = ""
SECURITY_CFLAGS_pn-loc-net-iface = ""
SECURITY_CFLAGS_pn-audiohal = ""
SECURITY_CFLAGS_pn-protobuf = ""
SECURITY_LDFLAGS_pn-protobuf = ""

