IMAGE_FSTYPES = "${INITRAMFS_FSTYPES}"

INITRAMFS_IMAGE = "machine-recovery-image"

BOOTIMAGE_TARGET = "${MACHINE}-recovery-boot.img"
BUNDLED_BOOTIMAGE_TARGET = "${MACHINE}-recovery-bundled-boot.img"

KERNEL_CMD_PARAMS_remove = "noinitrd"
KERNEL_CMD_PARAMS_append = " ramdisk_size=40960 DWC_ETH_QOS_platform.ipa_offload_en=0"

DEFAULT_ENFORCING = "permissive"

MACHINE_SUPPORTS_NAND_RECOVERY = "True"

KERNEL_IMAGENAME = "${@oe.utils.conditional('MACHINE_SUPPORTS_NAND_RECOVERY', 'True', '-nandrecovery', '', d)}"

# Disable usual recovery image generation.
RECOVERY_IMAGE = "0"
