#Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#SPDX-License-Identifier: BSD-3-Clause-Clear

## Generate vendor_dlkm image

DEPENDS += "cryptsetup-native"
DEPENDS += "fec-native avbtool-native"

# Convert human readable partition sizes into bytes
VDLKM_IMAGE_ROOTFS_SIZE = "${@get_size_in_bytes(d.getVar('VDLKM_SIZE_EXT4') or '32MB')}"

# Copy systemd modules-load.d configs from /etc to /lib/modules
# so that both modules and configs will be part of vdlkm image.
create_vdlkm_modules_load_d() {
    install -d ${IMAGE_ROOTFS}/lib/modules/modules-load.d/
    for conf in ${IMAGE_ROOTFS}${sysconfdir}/modules-load.d/*.conf; do
        install -D -m 0644 $conf ${IMAGE_ROOTFS}/lib/modules/modules-load.d/
        rm -f $conf
    done

    install -d ${IMAGE_ROOTFS}/lib/modules/modprobe.d/
    for conf in ${IMAGE_ROOTFS}${sysconfdir}/modprobe.d/*.conf; do
        install -D -m 0644 $conf ${IMAGE_ROOTFS}/lib/modules/modprobe.d/
        rm -f $conf
    done
}
ROOTFS_POSTPROCESS_COMMAND += "create_vdlkm_modules_load_d;"

# To successfully flash generated images on device, need to ensure combined size of
# unsparsed image and verity fec metadata is with in actual rootfs size. As there is
# no easy way to know the best fit values upfront, images and fec metadata are repeatedly
# generated by reducing size by 1% every time till a suitable image is avilable.
adjust_vdlkm_size() {
    #set -x
    adjustedSize=$(echo ${VDLKM_IMAGE_ROOTFS_SIZE} |egrep -o '^[0-9]+')
    percent=$(echo ${1} |egrep -o '^[0-9]+')
    adjustedSize=`expr $adjustedSize \* $percent`
    adjustedSize=`expr $adjustedSize / 100`

    #Align to 4096 block size
    adjustedSize=`expr $adjustedSize + 4095`
    adjustedSize=`expr $adjustedSize / 4096`
    adjustedSize=`expr $adjustedSize \* 4096`

    echo "$adjustedSize"
}

#$1 is path of vdlkm image.
get_verity_metdata_info(){
    VERITY_SALT="aee087a5be3b982978c923f566a94613496b417f2af592639bc80d141e34dfe7"
    FEC_ROOTS="2"

    # Remove files from previous run
    rm -f ${WORKDIR}/vdlkm.verityhash
    rm -f ${WORKDIR}/vdlkm.verityfec
    rm -f ${WORKDIR}/vdlkm_verity_metadata.txt

    veritysetup format $1 \
        ${WORKDIR}/vdlkm.verityhash \
        --fec-device ${WORKDIR}/vdlkm.verityfec \
        --fec-roots ${FEC_ROOTS} \
        --salt ${VERITY_SALT} > ${WORKDIR}/vdlkm_verity_metadata.txt
}

do_makevdlkm[dirs] = "${IMGDEPLOYDIR}/${IMAGE_BASENAME}"
do_makevdlkm() {
    if ${@bb.utils.contains('MACHINE_FEATURES', 'dm-verity-none', 'false', 'true', d)} ; then
    for count in {99..1}
    do
        invalid_image=0
        adjustedVdlkmSize=$(echo $(adjust_vdlkm_size "${count}" ))
        echo adjustedVdlkmSize: $adjustedVdlkmSize
        ImgPath="${IMGDEPLOYDIR}/${IMAGE_BASENAME}/${VDLKMIMAGE_UNSPARSE_TARGET}"
        make_ext4fs -B ${IMGDEPLOYDIR}/${IMAGE_BASENAME}/${VDLKMIMAGE_MAP_TARGET} \
                    -l ${adjustedVdlkmSize} ${ImgPath} \
                    ${IMAGE_ROOTFS}/lib/modules  /dev/null || invalid_image=1
        if [ $invalid_image -eq 1 ]; then
            echo "Unsparse image generation failed...exiting."
            break
        fi

        # Get verity metadata for generated image.
        get_verity_metdata_info "${ImgPath}"

        # Append hash and fec data to the image
        cat ${WORKDIR}/vdlkm.verityhash >> ${ImgPath}
        cat ${WORKDIR}/vdlkm.verityfec >> ${ImgPath}

        # Check if size is within the range
        vdlkmSize=`wc -c ${ImgPath} | awk '{print $1}'`
        if [ "$vdlkmSize" -gt "${VDLKM_IMAGE_ROOTFS_SIZE}" ]; then
            echo "Size mismatch ($vdlkmSize Vs ${VDLKM_IMAGE_ROOTFS_SIZE})...recreating unsparse image."
            continue
        fi

        # Calculate offset
        hash_offset=$adjustedVdlkmSize
        hash_size=`wc -c ${WORKDIR}/vdlkm.verityhash | awk '{print $1}'`
        fec_offset=`expr ${hash_offset} + ${hash_size}`
        echo "fec_offset:$fec_offset" >> ${WORKDIR}/vdlkm_verity_metadata.txt
        echo "Calculated fec offset: $fec_offset"

        # Convert to sparse image
        sparseImgPath="${IMGDEPLOYDIR}/${IMAGE_BASENAME}/${VDLKMIMAGE_TARGET}"
        img2simg ${ImgPath} ${sparseImgPath}

        echo "image is good to use..."
        break

    done
    elif ${@bb.utils.contains('MACHINE_FEATURES', 'qti-avb', bb.utils.contains('MACHINE_FEATURES', 'dm-verity-none', 'true', 'false', d), 'false', d)} ; then
        invalid_image=0
        adjustedVdlkmSize=$(avbtool.py add_hashtree_footer --partition_size ${VDLKM_IMAGE_ROOTFS_SIZE}  --calc_max_image_size)
        echo adjustedVdlkmSize: $adjustedVdlkmSize
        ImgPath="${IMGDEPLOYDIR}/${IMAGE_BASENAME}/${VDLKMIMAGE_UNSPARSE_TARGET}"
        make_ext4fs -B ${IMGDEPLOYDIR}/${IMAGE_BASENAME}/${VDLKMIMAGE_MAP_TARGET} \
                    -l ${adjustedVdlkmSize} ${ImgPath} \
                    ${IMAGE_ROOTFS}/lib/modules  /dev/null || invalid_image=1

        if [ $invalid_image -eq 1 ]; then
            echo "Unsparse image generation failed...exiting."
        fi

        VERITY_SALT="aee087a5be3b982978c923f566a94613496b417f2af592639bc80d141e34dfe7"

        avbtool.py add_hashtree_footer \
        --image ${ImgPath} \
        --partition_size  ${VDLKM_IMAGE_ROOTFS_SIZE} \
        --partition_name vendor_dlkm \
        --hash_algorithm sha256 \
        --fec_num_roots 2 \
        --salt ${VERITY_SALT} \
        --key ${STAGING_DIR_NATIVE}/${bindir}/SecImage/sigkeys/testkey_rsa4096.pem \
        --rollback_index 0

        # Convert to sparse image
        sparseImgPath="${IMGDEPLOYDIR}/${IMAGE_BASENAME}/${VDLKMIMAGE_TARGET}"
        img2simg ${ImgPath} ${sparseImgPath}

        echo "image is good to use..."
    else
        sparseImgPath="${IMGDEPLOYDIR}/${IMAGE_BASENAME}/${VDLKMIMAGE_TARGET}"
        make_ext4fs -s -B ${IMGDEPLOYDIR}/${IMAGE_BASENAME}/${VDLKMIMAGE_MAP_TARGET} \
                    -l ${VDLKM_IMAGE_ROOTFS_SIZE} ${sparseImgPath} \
                    ${IMAGE_ROOTFS}/lib/modules  /dev/null || invalid_image=1

        echo "image is good to use..."

    fi
}
# It must be before do_makesystem to remove /lib/modules
addtask do_makevdlkm after do_image before do_makesystem
