# Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted (subject to the limitations in the
# disclaimer below) provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#    * Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#       with the distribution.
#
#    * Neither the name of Qualcomm Innovation Center, Inc. nor the names of its
#      contributors may be used to endorse or promote products derived
#           from this software without specific prior written permission.
#
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE
# GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT
# HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

## Generate vendor_dlkm image

DEPENDS += "cryptsetup-native"

# Convert human readable partition sizes into bytes
VDLKM_IMAGE_ROOTFS_SIZE = "${@get_size_in_bytes(d.getVar('VDLKM_SIZE_EXT4') or '32MB')}"

# Copy systemd modules-load.d configs from /etc to /lib/modules
# so that both modules and configs will be part of vdlkm image.
create_vdlkm_modules_load_d() {
    install -d ${IMAGE_ROOTFS}/lib/modules/modules-load.d/
    for conf in ${IMAGE_ROOTFS}${sysconfdir}/modules-load.d/*.conf; do
        install -D -m 0644 $conf ${IMAGE_ROOTFS}/lib/modules/modules-load.d/
        rm -f $conf
    done
}
ROOTFS_POSTPROCESS_COMMAND += "create_vdlkm_modules_load_d;"

# To successfully flash generated images on device, need to ensure combined size of
# unsparsed image and verity fec metadata is with in actual rootfs size. As there is
# no easy way to know the best fit values upfront, images and fec metadata are repeatedly
# generated by reducing size by 1% every time till a suitable image is avilable.
adjust_vdlkm_size() {
    #set -x
    adjustedSize=$(echo ${VDLKM_IMAGE_ROOTFS_SIZE} |egrep -o '^[0-9]+')
    percent=$(echo ${1} |egrep -o '^[0-9]+')
    adjustedSize=`expr $adjustedSize \* $percent`
    adjustedSize=`expr $adjustedSize / 100`

    #Align to 4096 block size
    adjustedSize=`expr $adjustedSize + 4095`
    adjustedSize=`expr $adjustedSize / 4096`
    adjustedSize=`expr $adjustedSize \* 4096`

    echo "$adjustedSize"
}

#$1 is path of vdlkm image.
get_verity_metdata_info(){
    VERITY_SALT="aee087a5be3b982978c923f566a94613496b417f2af592639bc80d141e34dfe7"
    FEC_ROOTS="2"

    # Remove files from previous run
    rm -f ${WORKDIR}/vdlkm.verityhash
    rm -f ${WORKDIR}/vdlkm.verityfec
    rm -f ${WORKDIR}/vdlkm_verity_metadata.txt

    veritysetup format $1 \
        ${WORKDIR}/vdlkm.verityhash \
        --fec-device ${WORKDIR}/vdlkm.verityfec \
        --fec-roots ${FEC_ROOTS} \
        --salt ${VERITY_SALT} > ${WORKDIR}/vdlkm_verity_metadata.txt
}

do_makevdlkm[dirs] = "${IMGDEPLOYDIR}/${IMAGE_BASENAME}"
do_makevdlkm() {
    for count in {99..1}
    do
        invalid_image=0
        adjustedVdlkmSize=$(echo $(adjust_vdlkm_size "${count}" ))
        echo adjustedVdlkmSize: $adjustedVdlkmSize
        ImgPath="${IMGDEPLOYDIR}/${IMAGE_BASENAME}/${VDLKMIMAGE_UNSPARSE_TARGET}"
        make_ext4fs -B ${IMGDEPLOYDIR}/${IMAGE_BASENAME}/${VDLKMIMAGE_MAP_TARGET} \
                    -l ${adjustedVdlkmSize} ${ImgPath} \
                    ${IMAGE_ROOTFS}/lib/modules  /dev/null || invalid_image=1
        if [ $invalid_image -eq 1 ]; then
            echo "Unsparse image generation failed...exiting."
            break
        fi

        # Get verity metadata for generated image.
        get_verity_metdata_info "${ImgPath}"

        # Append hash and fec data to the image
        cat ${WORKDIR}/vdlkm.verityhash >> ${ImgPath}
        cat ${WORKDIR}/vdlkm.verityfec >> ${ImgPath}

        # Check if size is within the range
        vdlkmSize=`wc -c ${ImgPath} | awk '{print $1}'`
        if [ "$vdlkmSize" -gt "${VDLKM_IMAGE_ROOTFS_SIZE}" ]; then
            echo "Size mismatch ($vdlkmSize Vs ${VDLKM_IMAGE_ROOTFS_SIZE})...recreating unsparse image."
            continue
        fi

        # Calculate offset
        hash_offset=$adjustedVdlkmSize
        hash_size=`wc -c ${WORKDIR}/vdlkm.verityhash | awk '{print $1}'`
        fec_offset=`expr ${hash_offset} + ${hash_size}`
        echo "fec_offset:$fec_offset" >> ${WORKDIR}/vdlkm_verity_metadata.txt
        echo "Calculated fec offset: $fec_offset"

        # Convert to sparse image
        sparseImgPath="${IMGDEPLOYDIR}/${IMAGE_BASENAME}/${VDLKMIMAGE_TARGET}"
        img2simg ${ImgPath} ${sparseImgPath}

        echo "image is good to use..."
        break

    done
}
# It must be before do_makesystem to remove /lib/modules
addtask do_makevdlkm after do_image before do_makesystem
