# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2023-2025 Qualcomm Innovation Center, Inc. All rights reserved.

apps_pinctrl
scm_user_intf
qcom_dload_mode
arm-smmu-qcom-fusa
vfio_iommu_qcom
iommu_iova_map
kiumd
qcom_uscmi
kryo_arm64_edac
kiumd_kgsl
mhi_ep_net
socinfo
smem
qcom_hwspinlock
profiler
qcom_ethqos_filter

