require ${COREBASE}/../meta-agl/meta-agl/conf/distro/poky-agl.conf

INHERIT_remove += "uninative"

# Enable performance features
DISTRO_FEATURES += "qti-perf"

# support early_init feature
DISTRO_FEATURES_append = " early_init"

# Remove bluez, auto uses synergy by default
DISTRO_FEATURES_remove = "bluez5 bluetooth"
DISTRO_FEATURES_remove += "${@'wayland opengl' if '${MACHINE}' == '8x96autogvmquintcu' else ''}" 
DISTRO_FEATURES_remove += "${@'wifi' if '${MACHINE}' == '8x96autogvmquin' else ''}"
# TEMP FIX: retain existing directory structure for base product image.
DEPLOY_NAME ?= "${@base_contains('PRODUCT', 'base', '${MACHINE}', '${MACHINE}-${PRODUCT}', d)}-perf"
DEPLOY_DIR_IMAGE = "${DEPLOY_DIR}/images/${DEPLOY_NAME}"

TUNE_CCARGS .= "-march=armv8-a -mcpu=cortex-a57 -mtune=cortex-a57"

# Disable serial
SERIAL_CONSOLE=""

VIRTUAL-RUNTIME_net_manager_8x96autocv2x = "systemd"
