require ${COREBASE}/../meta-agl/meta-agl/conf/distro/poky-agl.conf

INHERIT_remove += "uninative"

DISTRO_FEATURES_remove += "bluez5 bluetooth"
DISTRO_FEATURES_remove += " 3g jrda pcmcia nfc libc-cxx-tests"
DISTRO_FEATURES_remove_8x96autodvrs += " pulseaudio"

# remove more reserve mm to work on 1G board
DISTRO_FEATURES_append_8x96autodvrs += " mm-diet"

# TEMP FIX: retain existing directory structure for base product image.
DEPLOY_NAME ?= "${@base_contains('PRODUCT', 'base', '${MACHINE}', '${MACHINE}-${PRODUCT}', d)}"
DEPLOY_DIR_IMAGE = "${DEPLOY_DIR}/images/${DEPLOY_NAME}"
