require conf/distro/auto.conf

# Enable performance features
DISTRO_FEATURES += "qti-perf"

# support early_init feature
# DISTRO_FEATURES += "early_init"

# support early-ethernet feature
DISTRO_FEATURES += "early-ethernet"

#If enable early_init/early-ethernet, remove pulseaudio from DISTRO_FEATURES 
DISTRO_FEATURES_remove += "${@'pulseaudio' if ('${DISTRO_FEATURES}'.find('early_init') >= 0 or '${DISTRO_FEATURES}'.find('early-ethernet') >= 0) and ('${WITH_INTERNAL_LAYER}' == 'no') else ''}"

# TEMP FIX: retain existing directory structure for base product image.
DEPLOY_NAME = "${@base_contains('PRODUCT', 'base', '${MACHINE}', '${MACHINE}-${PRODUCT}', d)}-perf"

# Disable serial
SERIAL_CONSOLE=""
