require ${COREBASE}/../meta-agl/meta-agl/conf/distro/poky-agl.conf

# Enable performance features
DISTRO_FEATURES += "qti-perf"
# Remove bluez, auto uses synergy by default
DISTRO_FEATURES_remove = "bluez5 bluetooth"
# TEMP FIX: retain existing directory structure for base product image.
DEPLOY_NAME ?= "${@base_contains('PRODUCT', 'base', '${MACHINE}', '${MACHINE}-${PRODUCT}', d)}-perf"
DEPLOY_DIR_IMAGE = "${DEPLOY_DIR}/images/${DEPLOY_NAME}"
