require ${COREBASE}/../meta-agl/meta-agl/conf/distro/poky-agl.conf

INHERIT_remove += "uninative"

# Remove bluez, auto uses synergy by default
DISTRO_FEATURES_remove = "bluez5 bluetooth"
DISTRO_FEATURES_remove += "${@'wayland opengl' if '${MACHINE}' == '8x96autogvmquintcu' else ''}"
DISTRO_FEATURES_remove += "${@'wifi' if '${MACHINE}' == '8x96autogvmquin' else ''}"
# TEMP FIX: retain existing directory structure for base product image.
DEPLOY_NAME ?= "${@base_contains('PRODUCT', 'base', '${MACHINE}', '${MACHINE}-${PRODUCT}', d)}"
DEPLOY_DIR_IMAGE = "${DEPLOY_DIR}/images/${DEPLOY_NAME}"

GNUPG_MIRROR = "https://www.gnupg.org/ftp/gcrypt"

BBMASK .= "|meta-gplv2/recipes-support/libiconv/libiconv_1.11.1.bb"
BBMASK .= "|meta-gplv2/recipes-devtools/rsync/rsync_2.6.9.bb"
BBMASK .= "|meta-gplv2/recipes-core/coreutils/coreutils_6.9.bb"

VIRTUAL-RUNTIME_net_manager_8x96autocv2x = "systemd"

INCOMPATIBLE_LICENSE = "GPL-3.0 LGPL-3.0 AGPL-3.0"
