BASEDISTRO ?= "auto"
require conf/distro/auto.conf

DISTRO_NAME = "nad-core"

PRODUCT = "auto"

# DM-Verity feature enabled/disabled under this distro. Uncomment to enable DM-Verity
DISTRO_FEATURES += "dm-verity"

# enable squahfs
DISTRO_FEATURES += "nand-squashfs"

DISTRO_FEATURES += "ab-boot-support"
DISTRO_FEATURES_NATIVE += "ab-boot-support"

# enable nand-ab
DISTRO_FEATURES += "nand-ab"

# NAD related partition changes are enabled under this distro
DISTRO_FEATURES += "nad-prod"

# enable modem-volume
DISTRO_FEATURES_append = " modem-volume"

# telaf specific features
DISTRO_FEATURES += "nad-telaf"

# Bundle initramfs image to kernel image
DISTRO_FEATURES += "initramfs"
