BASEDISTRO ?= "auto"
require conf/distro/auto.conf

DISTRO_NAME = "nad-core"

PRODUCT = "auto"

# DM-Verity feature enabled/disabled under this distro. Uncomment to enable DM-Verity
#DISTRO_FEATURES += "dm-verity"

# Uncomment to enable dm-verity working with avb feature in initramfs and root system
# For initramfs, it also need to enable the distro feature of "initramfs"
DISTRO_FEATURES += "nad-avb"

# enable squahfs
DISTRO_FEATURES += "nand-squashfs"

DISTRO_FEATURES += "ab-boot-support"
DISTRO_FEATURES_NATIVE += "ab-boot-support"

# enable nand-ab
DISTRO_FEATURES += "nand-ab"

# NAD related partition changes are enabled under this distro
DISTRO_FEATURES += "nad-prod"

# enable modem-volume
DISTRO_FEATURES_append = " modem-volume"

# Enable ZRAM as swap on RAM
DISTRO_FEATURES += "zram"

# telaf specific features
DISTRO_FEATURES += "nad-telaf"

# Bundle initramfs image to kernel image
DISTRO_FEATURES += "initramfs"

DISTRO_FEATURES_NATIVESDK_append = " nad-prod-sdk nad-avb"

DISTRO_FEATURES_append = " nad-prod-test"
