#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-fullstack-noselinux-nogplv3-debug
#@DESCRIPTION: Qualcomm Technologies Incorporated Full Reference Stack Linux Distribution
# (glibc based) having debugging capabilities without selinux support.
# Not optimized for performance. Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base           - provision for base distro variable overrides
#  * qti-distro-debug          - provision for debug distro variable overrides
#  * qti-distro-fullstack-noselinux-debug - provision for noselinux distro variable overrides
#
# For same variable override precedence order is
# qti-distro-fullstack-noselinux-debug > qti-distro-debug > qti-distro-base
#######################################################################################

# Honor qti-distro-debug override
DISTROOVERRIDES =. "qti-distro-debug:"

require conf/distro/include/qti-distro-fullstack.inc
require conf/distro/include/qti-distro-nogplv3.inc

DISTRO_NAME = "QTI Linux full reference stack debug capable distro without selinux."

# Remove selinux distro feature defined in fullstack distro.
DISTRO_FEATURES_remove = "selinux"

# Set DEBUG_BUILD to use flags from DEBUG_OPTIMIZATION variable
DEBUG_BUILD = "1"

# Bring in debug utilities.
DISTRO_EXTRA_RDEPENDS += "packagegroup-qti-debug-tools"

#enable systemd journal
SYSTEMD_ENABLE_JOURNAL = "1"

# GPLv2 package
PREFERRED_VERSION_gmp = "4.2.1"
PREFERRED_VERSION_nettle = "2.7.1"
PREFERRED_VERSION_libidn = "0.6.14"
PREFERRED_VERSION_gnutls = "3.3.30"
ERROR_QA_remove_gmp = "version-going-backwards"
ERROR_QA_remove_nettle = "version-going-backwards"
ERROR_QA_remove_gnutls = "version-going-backwards"
CFLAGS_append_pn-elfutils = " -Wno-error=format-truncation"
