
BASEDISTRO ?= "robot"
require conf/distro/msm.conf

DISTRO_NAME = "robot-ros"
DISTROOVERRIDES =. "robot-ros:"

SYSTEM_SIZE_EXT4 = "5368709120"

PRODUCT = "robot"
PREFERRED_VERSION_v4l-utils = "1.6.2"
