#! /bin/sh

# Copyright (c) 2018, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#   * Neither the name of The Linux Foundation nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

force_FDR() {
    echo  "Rebooting for FDR................" > /dev/console
    # Go for FDR
    userfs-reset y
}

clear_files_on_successful_fdr() {
    echo  "Start clearing files on successful FDR." > /dev/console

    target=$(cat /target)
    if [ -f /cache/$target.usrfs.tar ]; then
        rm /cache/$target.usrfs.tar
        echo  "Removed /cache/$target.usrfs.tar" > /dev/console
    fi

    if [ -f /cache/recovery/command ]; then
        if [ "$(cat /cache/recovery/command)" == "--wipe_data" ]; then
            rm /cache/recovery/command
            echo  "Removed /cache/recovery/command" > /dev/console
        fi
    fi

    if [ -f /cache/fdr/status ]; then
        rm -rf /cache/fdr
        echo  "Removed /cache/fdr/" > /dev/console
    fi

    echo  "Finished clearing files on successful FDR." > /dev/console
}

case "$1" in
  start )

    # If /cache/recovery/command exists
    if [ -f /cache/recovery/command ]; then
        echo  "mount-data: Found /cache/recovery/command file" > /dev/console

        # Check if command is "--wipe_data"
        if [ "$(cat /cache/recovery/command)" == "--wipe_data" ]; then
            echo  "mount-data: Command file has --wipe_data" > /dev/console

            # If /cache/fdr/status exists
            if [ -f /cache/fdr/status ]; then
                echo  "mount-data: /cache/fdr/status exists!!!!!!" > /dev/console

                # If status byte is "D", consider FDR completed
                if [ "$(cat /cache/fdr/status)" == "D" ]; then
                    echo  "Factory Reset Completed" > /dev/console

                else #If status byte in NOT "D"
                    echo  "mount-data: /cache/fdr/status has $(cat /cache/fdr/status)" > /dev/console
                    force_FDR
                    exit 0
                fi

            else # If /cache/fdr/status does NOT exist
                echo  "mount-data: missing /cache/fdr/status" > /dev/console
                force_FDR
                exit 0
            fi
        # If the /cache/recovery/command contains any other string, except "--wipe_data"
        # Ignore and proceed. As other commands are not part of FDR flow.
        fi
    else # If /cache/recovery/command does NOT exist
        if [ -f /cache/fdr/status ]; then
            # If status byte is "D", consider FDR completed
            if [ "$(cat /cache/fdr/status)" == "D" ]; then
                echo  "Factory Reset Completed........." > /dev/console

            else #If status byte in NOT "D"
                echo  "mount-data: No /cache/recovery/command file, was processed." > /dev/console
                echo  "mount-data: /cache/fdr/status has $(cat /cache/fdr/status)" > /dev/console
                force_FDR
                exit 0
            fi
        fi
        # If, both /cache/recovery/command and /cache/fdr/status both aren't there consider it to be
        # a non-FDR reboot cycle.
    fi

    #Attempt Mounting
    echo  "Mounting 'userdata' partition to /data" > /dev/console
    /bin/mount /dev/disk/by-partlabel/userdata /data
    if [ $? -ne 0 ]; then
        is_mounted=$(mount | grep "on.*\/data" | wc -l)
        if [ $is_mounted -eq 0 ]; then
            force_FDR
        else
            echo  "mount-data: /data mount-point in use" > /dev/console
        fi
    else
        clear_files_on_successful_fdr
    fi
    ;;

  stop )
    echo  "Unmount /data" > /dev/console
    umount /data
    ;;

  * )
    echo "Usage: mount-data {start | stop}"
    ;;
esac

exit 0
