require conf/distro/auto.conf

DISTRO_FEATURES_append = " qti-lxc qti-auto-lxc-overlay"

# Support selinux
DISTRO_FEATURES_append = " selinux"
DEFAULT_ENFORCING = "permissive"

PRODUCT = "${BASEMACHINE}lxc"
