require conf/distro/auto.conf

DISTRO_FEATURES_append = " qti-lxc qti-auto-lxc-overlay"

PRODUCT = "${BASEMACHINE}lxc"

#need this BBMASK to avoid build error
BBMASK .= "|meta-selinux/recipes-devtools/e2fsprogs/e2fsprogs_%.bbappend"

#refpolicy-qti corresponds to combined SELinux policy for LXC
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-qti"

DEFAULT_ENFORCING = "enforcing"
