require conf/distro/auto.conf

DISTRO_FEATURES_append = " qti-lxc qti-auto-lxc-overlay"

# Support selinux
DISTRO_FEATURES_append = " selinux"

# Support selinux
DISTRO_FEATURES_append = " selinux"

PRODUCT = "${BASEMACHINE}lxc"
