require conf/distro/include/auto-common.inc

DISTRO_NAME = "auto"

DISTRO_FEATURES_append = " qti-core qti-audio qti-data qti-extra qti-security qti-tools qti-graphics qti-display qti-camera qti-multimedia qti-ml qti-vnw"

