# Simple configure file for early-init program

[weston]
env=XDG_RUNTIME_DIR=@XDG_RUNTIME_DIR@
msleep=250
user=display
wait=/dev/dri/card0
cmd=/usr/bin/weston
argv=--tty=1
pidfile=/run/early/weston.pid
log=/run/weston.txt
<end>

[cvbs]
env=XDG_RUNTIME_DIR=@XDG_RUNTIME_DIR@
bindcpumask=12
priority=9
cmd=/usr/bin/cvbs
argv=-display=drm
argv=-deinterlace=bob
argv=-gpioValue=/sys/class/gpio/gpio109/value
pidfile=/run/early/cvbs.pid
log=/dev/null
gpio=109
<end>

[ais_server]
cmd=/usr/bin/ais_server
bindcpumask=12
priority=9
wait=/dev/early_driver_done
pidfile=/run/early/ais_server.pid
log=/dev/null
<end>

