# Simple configure file for early-init program

[weston]
env=XDG_RUNTIME_DIR=/early/user/0
wait=/dev/dri/card0
cmd=/usr/bin/weston
argv=--tty=1
pidfile=/early/weston.pid
log=/early/weston.txt
<end>

[ip_config]
cmd=/sbin/ifconfig
argv=eth0
argv=192.168.2.2
argv=up
log=/dev/null
<end>

[ethcam]
env=XDG_RUNTIME_DIR=/early/user/0
wait=/dev/early_driver_done
cmd=/usr/bin/ethcam
argv=0
argv=50001
argv=1
argv=0
argv=1
argv=1
argv=0
argv=0
argv=0
argv=0
argv=0
log=/dev/null
gpio=109
<end>
