# Simple configure file for early-init program

[cvbs]
wait=/dev/dri/card0
cmd=/usr/bin/cvbs
argv=-display
argv=-deinterlace=bob
argv=-gpioValue=/sys/class/gpio/gpio109/value
pidfile=/early/cvbs.pid
log=/dev/null
gpio=109
<end>

[ais_server]
cmd=/usr/bin/ais_server
wait=/dev/early_driver_done
pidfile=/early/ais_server.pid
log=/dev/null
<end>

