# Simple configure file for early-init program

[cvbs]
env=XDG_RUNTIME_DIR=/early/user/0
wait=/dev/dri/card0
cmd=/usr/bin/cvbs
argv=-display=drm
argv=-deinterlace=bob
argv=-gpioValue=/sys/class/gpio/gpio109/value
pidfile=/early/cvbs.pid
log=/dev/null
gpio=109
<end>

[weston]
env=XDG_RUNTIME_DIR=/early/user/0
wait=/dev/dri/card0
cmd=/usr/bin/weston
argv=--tty=1
pidfile=/early/weston.pid
log=/early/weston.txt
<end>

[ais_server]
cmd=/usr/bin/ais_server
wait=/dev/early_driver_done
pidfile=/early/ais_server.pid
log=/dev/null
<end>

