#@TYPE: Machine
#@NAME: LeMans
#@DESCRIPTION: Machine configuration for QTI LeMans

BASEMACHINE = "lemans"
include conf/machine/include/auto-common.inc

DEFAULTTUNE = "aarch64"
include conf/machine/include/arm/arch-armv8a.inc
TUNE_CCARGS:append = " -march=armv8-a -mcpu=cortex-a57 -mtune=cortex-a57"

PREFERRED_PROVIDER_mkbootimg-native = "mkbootimg-gki-native"
PREFERRED_VERSION_linux-msm = "5.15"
PREFERRED_VERSION_linux-msm-headers = "5.15"

PREFERRED_VERSION_adsprpc = "2.0"
PREFERRED_VERSION_edk2 = "4.0"
EDK2_USE_PREBUILTS = "True"

RECOVERY_IMAGE = "0"

KERNEL_ARCH = "gen4auto"
KERNEL_VARIANT = "${@bb.utils.contains_any('VARIANT', 'perf user', 'perf_', 'debug_', d)}"
KERNEL_BUILD_CONFIG = "msm-kernel/build.config.msm.${KERNEL_ARCH}.lxc"
KERNEL_IMAGE_HEADER_VERSION = "2"

KERNEL_BASE = "0x80000000"
KERNEL_TAGS_OFFSET = "0x1e00000"
KERNEL_CONFIG = "${@['vendor/${KERNEL_ARCH}-qgki_defconfig', 'vendor/${KERNEL_ARCH}-qgki-debug_defconfig'][d.getVar('VARIANT', True) == ('' or 'debug')]}"
KERNEL_CMD_PARAMS = "console=ttyMSM0,115200n8 earlycon=qcom_geni,0xa8c000 qcom_geni_serial.con_enabled=1 no_console_suspend=1 lpm_levels.sleep_disabled=1 rw rootwait rootfstype=ext4 firmware_class.path=/firmware/image/ nokaslr service_locator.enable=1 pcie_ports=compat"
KERNEL_CMD_PARAMS:append = " fsck.repair=yes "
KERNEL_CMD_PARAMS:remove = "${@bb.utils.contains_any('VARIANT', 'perf user', 'console=ttyMSM0,115200n8', '', d)}"
KERNEL_CMD_PARAMS:remove = "${@bb.utils.contains_any('VARIANT', 'perf user', 'earlycon=qcom_geni,0xa8c000', '', d)}"
KERNEL_CMD_PARAMS:remove = "${@bb.utils.contains('IMAGE_FEATURES', 'read-only-rootfs', 'rw', '', d)}"
KERNEL_IMAGETYPE = "Image"

# bootloader configuration
EXTRA_IMAGEDEPENDS += "edk2"

IMAGE_FEATURES:append = " read-only-rootfs"

MACHINE_FEATURES += "\
    qti-adsp \
    qti-cdsp \
    qti-core \
    qti-extra \
    qti-tools \
    qti-lxc \
    qti-graphics \
    qti-display \
    qti-wlan \
    qti-data \
    qti-vnw \
    qti-bluetooth \
"
MACHINE_FEATURES += "dt-overlay"

#MACHINE_EXTRA_RDEPENDS += "vpu-firmware"

SECTOOLS_VERSION = "sectools-v2"
