#@TYPE: Machine
#@NAME: quin-gvm-4gb
#@DESCRIPTION: Machine configuration for QTI QUIN

BASEMACHINE = "quin-gvm-4gb"
include conf/machine/include/auto-common.inc

#sa8195 board chip belongs to cortexa76-cortexa55
include conf/machine/include/tune-cortexa76-cortexa55.inc

SERIAL_CONSOLE = "115200 ttyAMA0"

KERNEL_BASE = "0x80000000"
KERNEL_TAGS_OFFSET = "0x1e00000"
KERNEL_CONFIG = "${@['vendor/autogvm-qgki_defconfig', 'vendor/autogvm-qgki-debug_defconfig'][d.getVar('VARIANT', True) == ('' or 'debug')]}"
KERNEL_CMD_PARAMS = " "
KERNEL_IMAGETYPE = "Image"

MACHINE_FEATURES += "\
    qti-audio \
    qti-bluetooth \
    qti-camera \
    qti-core \
    qti-data \
    qti-display \
    qti-dual-wlan \
    qti-extra \
    qti-graphics \
    qti-hypervisor \
    qti-ml \
    qti-multimedia \
    qti-security \
    qti-vnw \
    qti-wlan \
    qti-tools \
"

KERNEL_CMD_PARAMS:append = " console=ttyAMA0 loglevel=8 user_debug=31 print-fatal-signals=1 no_console_suspend firmware_class.path=/firmware/image/ fsck.repair=yes ip=192.168.1.2::192.168.1.10:255.255.255.0::eth0:none swiotlb=5120 kpti=1 pcie_ports=compat "
