#@TYPE: Machine
#@NAME: quin-gvm-lemans
#@DESCRIPTION: Machine configuration for QTI Quin GVM LEMANS(GEN4) Platform

BASEMACHINE ?= "quin-gvm-lemans"
include conf/machine/include/auto-common.inc

# Gen4(sa8295) board chip belongs to Cortex-A78C-Cortex-X1C
# GCC and Clang do not support Cortex-A78C-Cortex-X1C configurations yet.
# The highest configuration currently supported is Cortex-A78C(kirkstone)
include conf/machine/include/tune-cortexa78c.inc
# Tobe confirm machine inc
# DEFAULTTUNE = "aarch64"
# include conf/machine/include/arm/arch-armv8a.inc
# TUNE_CCARGS:append = " -march=armv8-a -mcpu=cortex-a57 -mtune=cortex-a57"

PREFERRED_PROVIDER_mkbootimg-native = "mkbootimg-gki-native"
PREFERRED_PROVIDER_dtc-native = "dtc-gki-native"

PREFERRED_VERSION_linux-msm = "5.15"
PREFERRED_VERSION_linux-msm-headers = "5.15"
PREFERRED_VERSION_adsprpc = "2.0"
PREFERRED_VERSION_media-codec2 = "auto.1.0"
PREFERRED_VERSION_media-external = "auto.1.0"

KERNEL_ARCH = "autogvm"
KERNEL_VARIANT = "${@bb.utils.contains_any('VARIANT', 'perf user', 'perf_', 'debug_', d)}"
KERNEL_BUILD_CONFIG = "msm-kernel/build.config.msm.${KERNEL_ARCH}.lxc"
KERNEL_IMAGE_HEADER_VERSION = "2"

KERNEL_BASE = "0x80000000"
KERNEL_TAGS_OFFSET = "0x1e00000"
KERNEL_CONFIG = "${@['vendor/autogvm_defconfig', 'vendor/autogvm-debug_defconfig'][d.getVar('VARIANT', True) == ('' or 'debug')]}"
KERNEL_CMD_PARAMS = " "
KERNEL_IMAGETYPE = "Image"

MACHINE_FEATURES += "\
    qti-adsp \
    qti-bluetooth \
    qti-cdsp \
    qti-core \
    qti-extra \
    qti-tools \
    qti-hypervisor \
    qti-data \
    qti-display \
    qti-graphics \
    qti-multimedia \
    qti-camera \
    qti-wlan \
    qti-security \
"
