#@TYPE: Machine
#@NAME: quin-gvm-monaco
#@DESCRIPTION: Machine configuration for QTI quin-gvm-monaco

BASEMACHINE = "quin-gvm-monaco"
include conf/machine/include/auto-common.inc

# Monaco board chip belongs to Cortex-A55-Cortex-a78C
# GCC and Clang do not support Cortex-A55-Cortex-a78C configurations yet.
# The highest big.LITTLE system currently supported is cortex-a76.cortex-a55.
include conf/machine/include/arm/armv8-2a/tune-cortexa76-cortexa55.inc

PREFERRED_PROVIDER_dtc-native = "dtc-aosp-native"

PREFERRED_VERSION_linux-msm = "6.1"
PREFERRED_VERSION_adsprpc = "2.0"
PREFERRED_VERSION_media-codec2 = "auto.1.0"
PREFERRED_VERSION_media-external = "auto.1.0"
PREFERRED_VERSION_media-noship = "auto.1.0"
PREFERRED_VERSION_codec2-service = "auto.1.0"

# monaco gvm prefer camx
PREFERRED_VERSION_cameradlkm = "0.2"

KERNEL_ARCH = "autogvm"
KERNEL_VARIANT = "${@bb.utils.contains_any('VARIANT', 'perf user', 'perf_', 'debug_', d)}"
KERNEL_BUILD_CONFIG = "msm-kernel/build.config.msm.${KERNEL_ARCH}.lxc"
KERNEL_IMAGE_HEADER_VERSION = "2"

KERNEL_BASE = "0x80000000"
KERNEL_TAGS_OFFSET = "0x1e00000"
KERNEL_CONFIG = "${@['vendor/autogvm_defconfig', 'vendor/autogvm-debug_defconfig'][d.getVar('VARIANT', True) == ('' or 'debug')]}"
KERNEL_CMD_PARAMS = " "
KERNEL_IMAGETYPE = "Image"

MACHINE_FEATURES += "\
    qti-core \
    qti-tools \
    qti-hypervisor \
    qti-data \
    qti-dlkm \
    qti-security \
    qti-bluetooth \
    qti-graphics \
    qti-wlan \
    qti-wlan-genoa \
    qti-camera \
    qti-display \
    qti-multimedia \
    qti-cdsp \
    qti-extra \
    qti-audio-ar \
    qti-vnw \
"
MACHINE_FEATURES:remove = "\
    qti-adsp \
    qti-cdsp1 \
    qti-bluetooth \
    qti-fastcv \
    qti-lxc \
"
