#@TYPE: Machine
#@NAME: sa81x5-rt
#@DESCRIPTION: Machine configuration for QTI sa81x5 RT

BASEMACHINE = "sa81x5"
include conf/machine/include/auto-common.inc

#sa81x5 board chip belongs to cortexa76-cortexa55
include conf/machine/include/tune-cortexa76-cortexa55.inc

RECOVERY_IMAGE = "0"

KERNEL_BASE = "0x80200000"
KERNEL_TAGS_OFFSET = "0x07D00000"
PAGE_SIZE = "2048"
KERNEL_RAMDISK_OFFSET = "0x00B00000"

KERNEL_CONFIG = "${@['vendor/gen3auto-qgki_defconfig', 'vendor/gen3auto-qgki-debug_defconfig'][d.getVar('VARIANT', True) == ('' or 'debug')]}"
KERNEL_CMD_PARAMS = "root=/dev/ram0 rw rootwait console=ttyMSM0,115200,n8 no_console_suspend=1 androidboot.hardware=qcom androidboot.console=ttyMSM0  lpm_levels.sleep_disabled=1 msm_rtb.filter=0x237 earlycon=qcom_geni,0xa90000 fips=0 notests nokaslr ignore_loglevel"

KERNEL_IMAGETYPE = "Image"

# bootloader configuration
EXTRA_IMAGEDEPENDS += "edk2"

IMAGE_FEATURES:append = " read-only-rootfs"

MACHINE_SUPPORTS_INIT_RAMDISK = "True"

MACHINE_FEATURES += "\ 
    qti-core \
    qti-audio \
    qti-bluetooth \
    qti-data \
    qti-display \
    qti-extra \
    qti-ml \
    qti-multimedia \
    qti-camera \
    qti-graphics \
    qti-security \
    qti-vnw \
    qti-wlan \
    qti-tools \
    qti-location \
"

