#SPDX-License-Identifier: GPL-2.0-only
#Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
snd_event_dlkm
q6_notifier_dlkm
gpr_dlkm
spf_core_dlkm
audpkt_ion_dlkm
q6_dlkm
adsp_loader_dlkm
audio_pkt_dlkm
audio_prm_dlkm
stub_dlkm
platform_dlkm
spf_machine_dlkm
wcd9xxx_dlkm
pinctrl_lpi_dlkm
