# FIXME: wlan driver will report wlan and p2p both as wlan in uevent
# which will mess connman, just ignore the p2p device by name
# the others are default one

[General]
NetworkInterfaceBlacklist = vmnet,vboxnet,virbr,ifb,ve-,vb-,p2p
PreferredTechnologies = ethernet,wifi,tun,cellular
TetheringTechnologies = ethernet,wifi
TetheringInterfaceBlacklist = eth0
PersistentTetheringEthernetMode = true
PreferredCellular = AT&T,Verizon,T-mobile
TetheringInterfaceNAT = eth0,wlan0,convergence0,rmnet_data0,rmnet_data8,rmnet_data16
