#*************Default eth0 Config **************#
mqprio_map0="0 2 1 2 3 2 2 2 2 2 2 2 2 2 2 2"
num_tc0=4
q2_idle_slope0=3648
q2_send_slope0=-996352
q2_hicredit0=12
q2_locredit0=-113
q3_idle_slope0=3648
q3_send_slope0=-996352
q3_hicredit0=12
q3_locredit0=-113
mqprio_handle0=100
q2_cbs_handle0=200
q3_cbs_handle0=250
q2_etf_handle0=275
q3_etf_handle0=300
tbs_enabled0=1

#*************Default eth1 Config **************#
mqprio_map1="0 2 1 2 3 2 2 2 2 2 2 2 2 2 2 2"
num_tc1=4
q2_idle_slope1=3648
q2_send_slope1=-996352
q2_hicredit1=12
q2_locredit1=-113
q3_idle_slope1=3648
q3_send_slope1=-996352
q3_hicredit1=12
q3_locredit1=-113
mqprio_handle1=400
q2_cbs_handle1=500
q3_cbs_handle1=550
q2_etf_handle1=575
q3_etf_handle1=600
tbs_enabled1=1
