qcom_tzmem
qcom-scm
msm_dma_iommu_mapping
qcom_iommu_debug
secure_buffer
deferred-free-helper
mem_buf_dev
qcom_dma_heaps
mem_buf_msgq
mem_buf
minidump_virtio
qcom_logbuf_boot_log
stub_regulator
qrtr
subsystem_notif_virt
smem
rproc_qcom_common
qcom_ipcc
qcom_glink
qcom_glink_smem
qcom_glink_cma
qcom_soc_wdt
gh_virt_wdt
usb_f_qdss
rsm_fe
hfastrpc
msm-geni-serial
pci-msm-drv
cfg80211
qrtr-mhi
spi_geni_qcom_msm
i2c_qcom_geni_msm
