qcom_tzmem
qcom-scm
msm_dma_iommu_mapping
qcom_iommu_debug
secure_buffer
deferred-free-helper
mem_buf_dev
qcom_dma_heaps
mem_buf_msgq
mem_buf
stub_regulator
qrtr
subsystem_notif_virt
smem
rproc_qcom_common
qcom_ipcc
qcom_glink
qcom_glink_smem
qcom_glink_cma
qcom_soc_wdt
usb_f_qdss
rsm_fe
hfastrpc
