SUMMARY = "Qualcomm soc-repo kernel modules"
DESCRIPTION = "Out-of-tree qualcomm kernel modules from soc-repo"
HOMEPAGE = "https://git.codelinaro.org"
LICENSE = "GPLv2.0-with-linux-syscall-note"
LIC_FILES_CHKSUM = "file://${WORKDIR}/kernel/kernel-${PV}/kernel_platform/soc-repo/COPYING;md5=6bc538ed5bd9a7fc9398086aedcd7e46"

COMPATIBLE_MACHINE = "gvm-gen4-5|gvm-gen5"

# soc-modules provides kernel-module-soc-modules, remove self-dependency
# added by qti-techpack.bbclass to avoid circular dependency.
DEPENDS:remove = "kernel-module-soc-modules"

# Provide kernel-module-soc-modules at recipe level so other OOT recipes
# (e.g. platformdlkm) can declare DEPENDS += "kernel-module-soc-modules"
# and module.bbclass automatically adds Module.symvers to KBUILD_EXTRA_SYMBOLS
# for cross-module symbol resolution (e.g. qcom_ssr_get_subsys needed by
# virtio_ssr.ko). PROVIDES satisfies build-time DEPENDS resolution.
PROVIDES += "kernel-module-soc-modules"

# Exclude .ko files from sysroot population: only Module.symvers (under
# ${includedir}) is needed by dependent recipes for KBUILD_EXTRA_SYMBOLS.
# Without this, all soc-modules .ko files get populated into the recipe-sysroot
# of every recipe that DEPENDS on kernel-module-soc-modules (e.g. platformdlkm,
# securemsmdlkm), bloating their sysroot with ~100 unneeded .ko files.
SYSROOT_DIRS:remove = "${nonarch_base_libdir}"

inherit qti-techpack

SRC_URI = "\
    ${PATH_TO_REPO}/kernel/kernel-${PV}/kernel_platform/common/.git;protocol=${PROTO};name=common;destsuffix=kernel/kernel-${PV}/kernel_platform/common;usehead=1 \
    ${PATH_TO_REPO}/kernel/kernel-${PV}/kernel_platform/soc-repo/.git;protocol=${PROTO};name=socrepo;destsuffix=kernel/kernel-${PV}/kernel_platform/soc-repo;usehead=1 \
    "
SRC_URI:append = " file://ack/0001-soc-repo-add-Kbuild-and-ufs-qcom-scmi-for-gvm-gen4-5.patch"

SRCREV_common = "${AUTOREV}"
SRCREV_socrepo = "${AUTOREV}"
SRCREV_FORMAT = "common_socrepo"

S = "${WORKDIR}/kernel/kernel-${PV}/kernel_platform/soc-repo"
SOC_REPO = "${WORKDIR}/kernel/kernel-${PV}/kernel_platform/soc-repo"

do_configure:prepend() {
    # Ensure KBA/Makefile points to kernel-source before configure runs.
    printf '# Automatically generated by %s/Makefile: do not edit\ninclude %s/Makefile\n' \
        "${STAGING_KERNEL_DIR}" "${STAGING_KERNEL_DIR}" \
        > "${STAGING_KERNEL_BUILDDIR}/Makefile"

    copy_common_sources
}

# copy_common_sources: mirror Bazel common_sources.bzl copy_file() behaviour.
# Copy ACK common/ source files into the soc-repo WORKDIR so that the OOT
# make build (make -C kernel-source O=KBA M=soc-repo/) can compile them.
# The soc-repo Makefiles already contain the obj-$(CONFIG_xxx) rules;
# only the .c sources are missing from soc-repo.
#
# Decision basis (diff common/ vs soc-repo/ per module):
#
#   virtio_console / virtio_input / i2c-virtio / net_failover / failover:
#     Single .c file, absent in soc-repo entirely -> plain cp of one file.
#
#   virtio_net:
#     Single .c file absent in soc-repo; soc-repo carries virtio_net_fix.diff
#     that must be applied to produce virtio_net_fixed.c (Makefile references
#     virtio_net_fixed.o, not virtio_net.o) -> patch -o (mirrors Bazel genrule).
#
#   cfg80211 (net/wireless/):
#     All .c/.h sources absent in soc-repo; soc-repo has only modules.bzl
#     (Bazel-only, irrelevant to make build) plus its own OOT Makefile and
#     tests/Makefile (both differ from common/ and must be preserved).
#     -> cp -r the whole directory from common/, then restore soc-repo's
#        Makefile and tests/Makefile which are OOT-specific.
copy_common_sources() {
    COMMON="${WORKDIR}/kernel/kernel-${PV}/kernel_platform/common"

    # --- 5 single-file copies ---
    cp -f "${COMMON}/drivers/char/virtio_console.c" \
          "${SOC_REPO}/drivers/char/"

    cp -f "${COMMON}/drivers/virtio/virtio_input.c" \
          "${SOC_REPO}/drivers/virtio/"

    cp -f "${COMMON}/drivers/i2c/busses/i2c-virtio.c" \
          "${SOC_REPO}/drivers/i2c/busses/"

    # net/core/ does not exist in soc-repo; failover.c is referenced as
    # ../../net/core/failover.o from drivers/net/Makefile.
    install -d "${SOC_REPO}/net/core"
    cp -f "${COMMON}/net/core/failover.c" \
          "${SOC_REPO}/net/core/"

    cp -f "${COMMON}/drivers/net/net_failover.c" \
          "${SOC_REPO}/drivers/net/"

    # --- virtio_net: patch -o (mirrors Bazel genrule exactly) ---
    # Bazel common_sources.bzl genrule:
    #   patch --follow-symlinks -o virtio_net_fixed.c \
    #         -i virtio_net_fix.diff common/drivers/net/virtio_net.c
    # Produces virtio_net_fixed.c without modifying the original source.
    # Makefile references virtio_net_fixed.o, not virtio_net.o.
    patch --follow-symlinks \
          -o "${SOC_REPO}/drivers/net/virtio_net_fixed.c" \
          -i "${SOC_REPO}/drivers/net/virtio_net_fix.diff" \
          "${COMMON}/drivers/net/virtio_net.c" || \
        bbfatal "soc-modules: failed to apply virtio_net_fix.diff"

    # --- cfg80211: cp -r whole directory, then restore soc-repo Makefiles ---
    # soc-repo net/wireless/ has only modules.bzl + its own OOT Makefile/tests/Makefile.
    # common/ has all .c/.h sources but its Makefiles are in-tree style (must NOT
    # overwrite soc-repo's OOT Makefiles).
    # Save soc-repo Makefiles, overwrite with common/, restore Makefiles.
    cp -f "${SOC_REPO}/net/wireless/Makefile" \
          "${WORKDIR}/wireless_Makefile.soc-repo"
    cp -f "${SOC_REPO}/net/wireless/tests/Makefile" \
          "${WORKDIR}/wireless_tests_Makefile.soc-repo"

    cp -rf "${COMMON}/net/wireless/." "${SOC_REPO}/net/wireless/"

    cp -f "${WORKDIR}/wireless_Makefile.soc-repo" \
          "${SOC_REPO}/net/wireless/Makefile"
    cp -f "${WORKDIR}/wireless_tests_Makefile.soc-repo" \
          "${SOC_REPO}/net/wireless/tests/Makefile"

    bbnote "soc-modules: copied ACK common/ sources into soc-repo workdir"
}

# Override base_do_configure: no make clean needed for OOT module source tree.
# auto.conf/autoconf.h patching is handled by make-mod-scripts:do_configure:append.
do_configure() {
    :
}

do_compile:prepend() {
    # Restore auto.conf/autoconf.h from .soc copies before make runs.
    # A previous recipe's do_compile may have triggered syncconfig which
    # overwrote auto.conf, losing soc-repo CONFIGs needed for this build.
    qti_techpack_restore_autoconf
}

# Use make -C kernel-source O=KBA M=soc-repo/ instead of make -C KBA M=soc-repo/.
# When -C KBA, abs_srctree=soc-repo (via KBA/Makefile->include soc-repo/Makefile)
# and abs_objtree=KBA, so building_out_of_srctree=1 and outputmakefile rewrites
# KBA/Makefile to "include soc-repo/Makefile", breaking subsequent OOT builds.
# When -C kernel-source O=KBA, abs_srctree=kernel-source and abs_objtree=KBA,
# outputmakefile writes "include kernel-source/Makefile" -- no change needed.
do_compile() {
    unset CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
    oe_runmake -C ${STAGING_KERNEL_DIR} \
        O=${STAGING_KERNEL_BUILDDIR} \
        M=${SOC_REPO} \
        KCONFIG_EXT_PREFIX=${SOC_REPO}/ \
        CC="${KERNEL_CC}" LD="${KERNEL_LD}" \
        AR="${KERNEL_AR}" OBJCOPY="${KERNEL_OBJCOPY}" \
        STRIP="${KERNEL_STRIP}" \
        HOSTCC="${BUILD_CC}" HOSTCFLAGS="${BUILD_CFLAGS}" \
        HOSTLDFLAGS="${BUILD_LDFLAGS}" HOSTCPP="${BUILD_CPP}" \
        HOSTCXX="${BUILD_CXX}" HOSTCXXFLAGS="${BUILD_CXXFLAGS}" \
        DTC="${STAGING_KERNEL_BUILDDIR}/scripts/dtc/dtc" \
        DTC_INCLUDE="${SOC_REPO}/scripts/dtc/include-prefixes/ ${STAGING_KERNEL_DIR}/scripts/dtc/include-prefixes/" \
        KBUILD_EXTRA_SYMBOLS="${KBUILD_EXTRA_SYMBOLS}" \
        NOSTDINC_FLAGS="-I${SOC_REPO}/include \
                        -I${SOC_REPO}/include/linux \
                        -I${SOC_REPO}/include/uapi \
                        -I${SOC_REPO}/arch/arm64/include \
                        -I${SOC_REPO}/arch/arm64/include/uapi \
                        -I${STAGING_KERNEL_DIR} \
                        -nostdinc" \
        KCFLAGS=" -Wno-implicit-function-declaration -Wno-unused-variable \
                -Wno-parentheses -Wno-implicit-fallthrough -Wno-out-of-line-declaration \
                -Wno-misleading-indentation -Wno-visibility" \
        modules
}

do_install() {
    # Install .ko files to ${D} (standard bitbake install destination).
    # do_install must not write to STAGING_KERNEL_BUILDDIR (work-shared/)
    # as pseudo aborts on cross-recipe writes during do_install.
    install -d ${D}${nonarch_base_libdir}/modules/${KERNEL_VERSION}
    for mod in $(find ${SOC_REPO} -name '*.ko'); do
        [ -f "$mod" ] && install -m 0644 "$mod" \
            ${D}${nonarch_base_libdir}/modules/${KERNEL_VERSION}
    done

    rm -rf ${D}${nonarch_base_libdir}/modules/${KERNEL_VERSION}/updates/

    # Install Module.symvers so other OOT modules (e.g. platformdlkm) can
    # resolve symbols exported by soc-modules (e.g. qcom_ssr_get_subsys).
    # Use "kernel-module-soc-modules" prefix so module.bbclass automatically
    # adds it to KBUILD_EXTRA_SYMBOLS when "kernel-module-soc-modules" is
    # listed in DEPENDS of the consumer recipe (module.bbclass line 18-19:
    # for dep in DEPENDS: if dep.startswith("kernel-module-"): add symvers).
     if [ -f ${SOC_REPO}/Module.symvers ]; then
         install -Dm0644 ${SOC_REPO}/Module.symvers \
             ${D}${includedir}/kernel-module-soc-modules/Module.symvers
     fi
}

FILES:${PN} += "${includedir}/kernel-module-soc-modules/*"
