# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "qti-distro"
BBFILE_PATTERN_qti-distro = "^${LAYERDIR}/"
BBFILE_PRIORITY_qti-distro = "10"

LAYERSERIES_COMPAT_qti-distro = "kirkstone"

QTI_METAPATH_DISTRO := '${@os.path.normpath("${LAYERDIR}/")}'
