# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

#Conf file to load security-driver modules at boot-up time
#Install under /etc/modules-load-d/ path
qseecom_dlkm
qrng_dlkm
