# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"
BSPDIR := "${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)) + '/../../..')}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILES_DYNAMIC += " \
    aglcore:${LAYERDIR}/dynamic-layers/meta-agl-core/*/*/*.bb \
    aglcore:${LAYERDIR}/dynamic-layers/meta-agl-core/*/*/*.bbappend \
    agldemo:${LAYERDIR}/dynamic-layers/meta-agl-demo/*/*/*.bb \
    agldemo:${LAYERDIR}/dynamic-layers/meta-agl-demo/*/*/*.bbappend \
    meta-qti-dpk:${LAYERDIR}/dynamic-layers/meta-qti-dpk/*/*/*.bb \
    meta-qti-dpk:${LAYERDIR}/dynamic-layers/meta-qti-dpk/*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "qti"
BBFILE_PATTERN_qti = "^${LAYERDIR}/"
BBFILE_PRIORITY_qti = "10"

LAYERSERIES_COMPAT_qti = "kirkstone"

LAYERDEPENDS_qti = "core openembedded-layer networking-layer multimedia-layer qti-upstream qti-prop"

LICENSE_PATH += "${LAYERDIR}/files/common-licenses"

# Currently edk2 need python2 to support compilation
HOSTTOOLS_NONFATAL += "python python2"

QTI_METAPATH_BASE := '${@os.path.normpath("${LAYERDIR}/")}'
QTI_LICENSE_DIR = "${QTI_METAPATH_BASE}/files/common-licenses"
