# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "qti"
BBFILE_PATTERN_qti = "^${LAYERDIR}/"
BBFILE_PRIORITY_qti = "10"

LAYERSERIES_COMPAT_qti = "dunfell gatesgarth hardknott"

LAYERDEPENDS_qti = "core openembedded-layer networking-layer multimedia-layer qti-upstream qti-prop"

# Tools needed on the build host for usage within build tasks by recipes of this layer.
HOSTTOOLS_NONFATAL += "xgettext msgmerge msgfmt gmsgfmt java zip python python2 flex bison"

QTI_METAPATH_BASE := '${@os.path.normpath("${LAYERDIR}/")}'
